In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(r'C:\Users\Incognitus\Documents\раб_данные\data_work.xlsx')

C:\Users\Incognitus\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [3]:
df.columns

Index(['Дата/время регистрации', ' ', 'Номер', 'Статус', 'Приоритет',
       'Получатель услуг', 'Инициатор', 'Расположение', 'Описание',
       'Фактическое время выполнения', '     Услуга', '    Компонент услуги',
       '   Вид запроса', 'Площадка обслуживания пользователя',
       'Техническое описание', 'Головной запрос', '  Конфигурационные единицы',
       'Текущий ответственный', 'Кем решен (сотрудник)',
       'Кто выполняет контроль? (Сотрудник)', 'Плановое время выполнения',
       'Просрочен', '     Результат работ', '     Описание решения',
       'Количество уточнений', 'Количество возобновлений',
       'Качество проведения работ по Запросу',
       'Статус исполнения дочерних запросов', 'Крайний срок обработки',
       'Крайний срок обработки ТО', 'Отложенный запрос',
       'Время входа в статус'],
      dtype='object')

In [4]:
df.head(1)

,Дата/время регистрации,,Номер,Статус,Приоритет,Получатель услуг,Инициатор,Расположение,Описание,Фактическое время выполнения,...,Результат работ,Описание решения,Количество уточнений,Количество возобновлений,Качество проведения работ по Запросу,Статус исполнения дочерних запросов,Крайний срок обработки,Крайний срок обработки ТО,Отложенный запрос,Время входа в статус
0,2020-07-29 16:57:41.315,Запрос на обслуживание,RP2634178,Закрыт,(4) Низкий,Парменов Сергей Анатольевич,Парменов Сергей Анатольевич,ПАТЭС Спб,Обновление антивирусных баз Добрый день. Прошу...,2020-07-30 08:56:31.214,...,Решение предоставлено,Уважаемый Сергей Анатольевич! Ваша заявка была...,0,0,0,NaN,2020-08-17 11:27:50.526,NaN,NaN,2020-08-06 09:00:09.198

In [5]:
applications = df.loc[:,['Дата/время регистрации', 'Крайний срок обработки', 'Фактическое время выполнения', 'Плановое время выполнения', 'Приоритет', 'Просрочен', '     Результат работ', 'Получатель услуг', 'Инициатор', 'Кем решен (сотрудник)', 'Расположение', 'Описание', '     Услуга', '    Компонент услуги', '   Вид запроса', 'Площадка обслуживания пользователя']]

In [6]:
applications.head(5)

,Дата/время регистрации,Крайний срок обработки,Фактическое время выполнения,Плановое время выполнения,Приоритет,Просрочен,Результат работ,Получатель услуг,Инициатор,Кем решен (сотрудник),Расположение,Описание,Услуга,Компонент услуги,Вид запроса,Площадка обслуживания пользователя
0,2020-07-29 16:57:41.315,2020-08-17 11:27:50.526,2020-07-30 08:56:31.214,2020-08-10 11:27:41.315,(4) Низкий,не просрочен,Решение предоставлено,Парменов Сергей Анатольевич,Парменов Сергей Анатольевич,Аширов Юрий Алексеевич,ПАТЭС Спб,Обновление антивирусных баз Добрый день. Прошу...,ИТ-АРМ,ИТ-14-7-1 Автоматизированное рабочее место с о...,4. Настройка / обновление ПО,Плавучая атомная теплоэлектростанция
1,2020-09-03 17:12:25.514,2020-09-22 11:48:43.947,2020-09-04 10:37:38.608,2020-09-15 11:00:00.000,(4) Низкий,не просрочен,Решение предоставлено,Глушкова Наталья Александровна,Глушкова Наталья Александровна,Катанов Антон Сергеевич,Ленинградская АЭС,"Портал: Заявка на доступ к ИС ""Организация раб...",ИТ-АРМ,ИТ-14-7 Программная поддержка рабочего места н...,Запрос на обслуживание,Ленинградская АЭС
2,2020-12-24 11:10:54.874,2021-01-15 15:28:52.818,2020-12-24 16:23:14.968,2020-12-31 15:25:54.874,(4) Низкий,не просрочен,Решение предоставлено,Яцына Светлана Александровна,Коротицкий Николай Анатольевич,Коротицкий Николай Анатольевич,Ленинградская АЭС-2,"Проверить клиент Horizon, настроить почтовый к...",ИТ-АРМ,ИТ-14-37 Программная поддержка рабочего места ...,Настройка / обновление ПО,Ленинградская АЭС-2
3,2021-02-12 15:05:12.186,2021-03-05 09:37:28.359,2021-02-12 15:23:53.645,2021-02-26 09:35:12.186,(4) Низкий,не просрочен,Решение предоставлено,Мосалева Елена Алексеевна,Мосалева Елена Алексеевна,Аширов Юрий Алексеевич,ПАТЭС Спб,Настроить CheckPoint VPN.,ИТ-АРМ,ИТ-14-7-1 Автоматизированное рабочее место с о...,4. Настройка / обновление ПО,Плавучая атомная теплоэлектростанция
4,2021-02-11 08:40:34.669,2021-02-25 12:59:19.790,2021-02-15 11:15:40.259,2021-02-16 15:15:00.000,(4) Низкий,не просрочен,Отменен,Щербаков Анатолий Максимович,Щербаков Анатолий Максимович,Струсинский Павел Михайлович,ЦА Москва,срочно!!! Прошу обеспечить доступ к оперативно...,ИТ-Система КЦ,ИТ-11-9-1 Программный комплекс представления в...,Запрос на обслуживание,Ленинградская АЭС

In [7]:
for col_name in df.columns:
    print(col_name)

Дата/время регистрации

Номер
Статус
Приоритет
Получатель услуг
Инициатор
Расположение
Описание
Фактическое время выполнения
     Услуга
    Компонент услуги
   Вид запроса
Площадка обслуживания пользователя
Техническое описание
Головной запрос
  Конфигурационные единицы
Текущий ответственный
Кем решен (сотрудник)
Кто выполняет контроль? (Сотрудник)
Плановое время выполнения
Просрочен
     Результат работ
     Описание решения
Количество уточнений
Количество возобновлений
Качество проведения работ по Запросу
Статус исполнения дочерних запросов
Крайний срок обработки
Крайний срок обработки ТО
Отложенный запрос
Время входа в статус

In [8]:
import pandas as pd
import hashlib

# Предполагаем, что ваш df уже загружен и называется applications
# Если нет - раскомментируйте следующую строку:
# applications = pd.read_csv('ваш_файл.csv', encoding='utf-8')

# Очищаем названия колонок от лишних пробелов
applications.columns = applications.columns.str.strip()

# --- 1. Анализ уникальных значений ДО анонимизации ---
print("="*60)
print("АНАЛИЗ ДО АНОНИМИЗАЦИИ")
print("="*60)

# Список колонок с именами
name_columns = ['Получатель услуг', 'Инициатор', 'Кем решен (сотрудник)']

# Словарь для хранения статистики
stats_before = {}

for col in name_columns:
    if col in applications.columns:
        # Убираем пустые значения и считаем уникальные
        unique_values = applications[col].dropna().unique()
        num_unique = len(unique_values)
        stats_before[col] = {
            'count': num_unique,
            'sample': unique_values[:5]  # Покажем первые 5 для примера
        }
        
        print(f"\nКолонка: {col}")
        print(f"  Уникальных значений: {num_unique}")
        print(f"  Примеры (первые 5): {unique_values[:5]}")
        print(f"  Всего записей в колонке: {applications[col].count()}")
    else:
        print(f"\nКолонка {col} не найдена!")

# Общее количество уникальных людей (объединение всех трех колонок)
all_unique_people = pd.unique(applications[name_columns].values.ravel())
all_unique_people = [p for p in all_unique_people if pd.notna(p)]  # Убираем NaN
print(f"\n{'='*60}")
print(f"ВСЕГО уникальных людей во всех колонках: {len(all_unique_people)}")
print(f"Примеры: {all_unique_people[:10]}")

============================================================
АНАЛИЗ ДО АНОНИМИЗАЦИИ
============================================================

Колонка: Получатель услуг
  Уникальных значений: 3709
  Примеры (первые 5): ['Парменов Сергей Анатольевич' 'Глушкова Наталья Александровна'
 'Яцына Светлана Александровна' 'Мосалева Елена Алексеевна'
 'Щербаков Анатолий Максимович']
  Всего записей в колонке: 18992

Колонка: Инициатор
  Уникальных значений: 3585
  Примеры (первые 5): ['Парменов Сергей Анатольевич' 'Глушкова Наталья Александровна'
 'Коротицкий Николай Анатольевич' 'Мосалева Елена Алексеевна'
 'Щербаков Анатолий Максимович']
  Всего записей в колонке: 18992

Колонка: Кем решен (сотрудник)
  Уникальных значений: 152
  Примеры (первые 5): ['Аширов Юрий Алексеевич' 'Катанов Антон Сергеевич'
 'Коротицкий Николай Анатольевич' 'Струсинский Павел Михайлович'
 'Завадецкий Владимир Васильевич']
  Всего записей в колонке: 18889

============================================================
ВСЕГО уникальных людей во всех колонках: 3837
Примеры: ['Парменов Сергей Анатольевич', 'Аширов Юрий Алексеевич', 'Глушкова Наталья Александровна', 'Катанов Антон Сергеевич', 'Яцына Светлана Александровна', 'Коротицкий Николай Анатольевич', 'Мосалева Елена Алексеевна', 'Щербаков Анатолий Максимович', 'Струсинский Павел Михайлович', 'Снежков Георгий Юрьевич']

In [9]:
# --- 2. Создаем маппинг "Реальное имя -> ID" ---
print("\n" + "="*60)
print("СОЗДАНИЕ МАППИНГА")
print("="*60)

# Собираем все уникальные имена из всех трех колонок
all_names = []
for col in name_columns:
    all_names.extend(applications[col].dropna().unique())

# Оставляем только уникальные имена
unique_names = list(set(all_names))
unique_names = [name for name in unique_names if pd.notna(name)]  # Убираем NaN

print(f"Всего уникальных имен для маппинга: {len(unique_names)}")

# Создаем словарь имя -> ID
name_to_id = {}
for name in unique_names:
    if pd.notna(name) and name != '':
        # Создаем хеш от имени
        hash_object = hashlib.md5(str(name).encode('utf-8'))
        hash_hex = hash_object.hexdigest()[:8]
        user_id = f"User_{hash_hex}"
        name_to_id[name] = user_id

# Покажем примеры маппинга
print("\nПримеры маппинга (первые 10):")
for i, (name, user_id) in enumerate(list(name_to_id.items())[:10]):
    print(f"  {name} -> {user_id}")

# Проверяем, что все имена попали в словарь
print(f"\nРазмер словаря: {len(name_to_id)} имен")
print(f"Уникальных имен для маппинга: {len(unique_names)}")
print(f"Совпадение: {len(name_to_id) == len(unique_names)}")

============================================================
СОЗДАНИЕ МАППИНГА
============================================================
Всего уникальных имен для маппинга: 3837

Примеры маппинга (первые 10):
  Шикова Елена Николаевна -> User_d2b8058b
  Казакова Наталья Игоревна -> User_830e4454
  Фадеев Антон Михайлович -> User_516114ab
  Пичугина Татьяна Анатольевна -> User_033955c8
  Медведева Анастасия Игоревна -> User_ad611e25
  Розидеев Дмитрий Сергеевич -> User_f222d779
  Осипов Никита Олегович -> User_032b3054
  Дирекция строящейся Балтийской АЭС -> User_6338fb0e
  Жолобов Владимир Сергеевич -> User_ee5e2b55
  Осипов Илья Сергеевич -> User_8fabaf26

Размер словаря: 3837 имен
Уникальных имен для маппинга: 3837
Совпадение: True

In [10]:
# --- 3. Применяем анонимизацию ---
print("\n" + "="*60)
print("ПРИМЕНЕНИЕ АНОНИМИЗАЦИИ")
print("="*60)

# Создаем копию, чтобы не менять исходные данные
applications_anon = applications.copy()

# Применяем маппинг к каждой колонке
for col in name_columns:
    if col in applications_anon.columns:
        # Заменяем имена на ID, оставляя NaN без изменений
        applications_anon[col] = applications_anon[col].map(name_to_id).fillna(applications_anon[col])
        
        # Проверяем, что замена произошла
        unique_after = applications_anon[col].dropna().unique()
        print(f"\nКолонка {col}:")
        print(f"  Уникальных значений после замены: {len(unique_after)}")
        print(f"  Примеры ID: {unique_after[:5]}")

============================================================
ПРИМЕНЕНИЕ АНОНИМИЗАЦИИ
============================================================

Колонка Получатель услуг:
  Уникальных значений после замены: 3709
  Примеры ID: ['User_5690b13b' 'User_9d645efd' 'User_7b6353d9' 'User_209ccc4f'
 'User_2f226a4b']

Колонка Инициатор:
  Уникальных значений после замены: 3585
  Примеры ID: ['User_5690b13b' 'User_9d645efd' 'User_2e984f36' 'User_209ccc4f'
 'User_2f226a4b']

Колонка Кем решен (сотрудник):
  Уникальных значений после замены: 152
  Примеры ID: ['User_27e54663' 'User_c79cd486' 'User_2e984f36' 'User_7881f410'
 'User_fd851d02']

In [11]:
# --- 4. Финальная проверка ---
print("\n" + "="*60)
print("ФИНАЛЬНАЯ ПРОВЕРКА")
print("="*60)

# Проверяем каждую колонку
print("\nПОКОЛОННОЕ СРАВНЕНИЕ:")
print("-" * 40)

for col in name_columns:
    # Уникальные ДО (без NaN)
    unique_before = set(applications[col].dropna().unique())
    # Уникальные ПОСЛЕ (без NaN)
    unique_after = set(applications_anon[col].dropna().unique())
    
    print(f"\n{col}:")
    print(f"  Уникальных ДО: {len(unique_before)}")
    print(f"  Уникальных ПОСЛЕ: {len(unique_after)}")
    print(f"  Совпадает ли количество? {'ДА' if len(unique_before) == len(unique_after) else 'НЕТ'}")
    
    # Дополнительная проверка: если есть несовпадение, покажем разницу
    if len(unique_before) != len(unique_after):
        print(f"  ВНИМАНИЕ: Несовпадение количества!")

# Проверяем общее количество уникальных людей во всех колонках
all_unique_before = set()
all_unique_after = set()

for col in name_columns:
    all_unique_before.update(applications[col].dropna().unique())
    all_unique_after.update(applications_anon[col].dropna().unique())

print(f"\n{'='*60}")
print(f"ИТОГО УНИКАЛЬНЫХ ЛЮДЕЙ (во всех колонках):")
print(f"  ДО анонимизации: {len(all_unique_before)}")
print(f"  ПОСЛЕ анонимизации: {len(all_unique_after)}")
print(f"  Результат: {'✓ ВСЕ СОХРАНЕНО' if len(all_unique_before) == len(all_unique_after) else '✗ ЕСТЬ ПОТЕРИ'}")

============================================================
ФИНАЛЬНАЯ ПРОВЕРКА
============================================================

ПОКОЛОННОЕ СРАВНЕНИЕ:
----------------------------------------

Получатель услуг:
  Уникальных ДО: 3709
  Уникальных ПОСЛЕ: 3709
  Совпадает ли количество? ДА

Инициатор:
  Уникальных ДО: 3585
  Уникальных ПОСЛЕ: 3585
  Совпадает ли количество? ДА

Кем решен (сотрудник):
  Уникальных ДО: 152
  Уникальных ПОСЛЕ: 152
  Совпадает ли количество? ДА

============================================================
ИТОГО УНИКАЛЬНЫХ ЛЮДЕЙ (во всех колонках):
  ДО анонимизации: 3837
  ПОСЛЕ анонимизации: 3837
  Результат: ✓ ВСЕ СОХРАНЕНО

In [12]:
# --- 5. Сохраняем анонимизированный датасет и маппинг ---

# Сохраняем основной датасет
applications_anon.to_csv(r'C:\Users\Incognitus\Documents\раб_данные\applications_anonymized.csv', index=False, encoding='utf-8-sig')
print("\n✓ Анонимизированный датасет сохранен: 'applications_anonymized.csv'")

# Сохраняем маппинг на случай, если понадобится расшифровка (но обычно это не нужно)
mapping_df = pd.DataFrame(list(name_to_id.items()), columns=['Original_Name', 'User_ID'])
mapping_df.to_csv('name_mapping.csv', index=False, encoding='utf-8-sig')
print("✓ Маппинг имен сохранен: 'name_mapping.csv' (храните в безопасном месте)")

# Покажем финальный результат
print("\n" + "="*60)
print("ПРИМЕР РЕЗУЛЬТАТА (первые 3 строки):")
print("="*60)
print("\nДО анонимизации:")
print(applications[name_columns].head(3))

print("\nПОСЛЕ анонимизации:")
print(applications_anon[name_columns].head(3))

✓ Анонимизированный датасет сохранен: 'applications_anonymized.csv'
✓ Маппинг имен сохранен: 'name_mapping.csv' (храните в безопасном месте)

============================================================
ПРИМЕР РЕЗУЛЬТАТА (первые 3 строки):
============================================================

ДО анонимизации:
                 Получатель услуг                       Инициатор  \
0     Парменов Сергей Анатольевич     Парменов Сергей Анатольевич
1  Глушкова Наталья Александровна  Глушкова Наталья Александровна
2    Яцына Светлана Александровна  Коротицкий Николай Анатольевич

            Кем решен (сотрудник)
0          Аширов Юрий Алексеевич
1         Катанов Антон Сергеевич
2  Коротицкий Николай Анатольевич

ПОСЛЕ анонимизации:
  Получатель услуг      Инициатор Кем решен (сотрудник)
0    User_5690b13b  User_5690b13b         User_27e54663
1    User_9d645efd  User_9d645efd         User_c79cd486
2    User_7b6353d9  User_2e984f36         User_2e984f36

In [13]:
applications.columns

Index(['Дата/время регистрации', 'Крайний срок обработки',
       'Фактическое время выполнения', 'Плановое время выполнения',
       'Приоритет', 'Просрочен', 'Результат работ', 'Получатель услуг',
       'Инициатор', 'Кем решен (сотрудник)', 'Расположение', 'Описание',
       'Услуга', 'Компонент услуги', 'Вид запроса',
       'Площадка обслуживания пользователя'],
      dtype='object')

In [14]:
df_part2 = applications.loc[:, ['Расположение', 'Описание', 'Услуга', 'Вид запроса']]

In [15]:
df_part2.head(3)

,Расположение,Описание,Услуга,Вид запроса
0,ПАТЭС Спб,Обновление антивирусных баз Добрый день. Прошу...,ИТ-АРМ,4. Настройка / обновление ПО
1,Ленинградская АЭС,"Портал: Заявка на доступ к ИС ""Организация раб...",ИТ-АРМ,Запрос на обслуживание
2,Ленинградская АЭС-2,"Проверить клиент Horizon, настроить почтовый к...",ИТ-АРМ,Настройка / обновление ПО

In [16]:
# Атомные станции
applications['Расположение'].nunique()

18

In [17]:
# описание придумать новое 
applications['Описание'].unique()

array(['Обновление антивирусных баз Добрый день. Прошу до 03.08.2020 провести обновление антивирусных баз на рабочих местах пользователей ПАТЭС (Певек, Москва, Санкт-Петербург, в том числе удалённых), серверном оборудовании и внутри виртуальной среды. Информацию о выполнении направить на имя Парменова Сергея Анатольевича parmenov-sa@rosenergoatom.ru С уважением, Пармёнов Сергей Анатольевич',
       'Портал: Заявка на доступ к ИС "Организация рабочего места" Просьба предоставить полномочия на доступ к ИТ-ресурсам по заявке N 81733 Заявитель: Глушкова Наталья Александровна, Старший бухгалтер',
       'Проверить клиент Horizon, настроить почтовый клиент Evolution.',
       ...,
       'Здравствуйте! Не получается выполнить вход в ИСУиАС. Заходит в Remmina, а дальше этот же логин и пароль не принимает IP адрес: 10.3.96.84 KE 139178 Версия ОС 1.7.5 Номер устройства: 3216 Тип устройства: Компьютер ФИО: Саноцкий Павел Сергеевич Подразделение: ОДМиТК Здание: 401 Помещение: 911 Телефон: 51093 Email: odm-sps@ln.rosenergoatom.ru',
       'Не работает удаленный рабочий стол , темный экран IP 10.3.160.101 тел: 5-34-79',
       '10.107.25.4 ошибка в ЕОСДО т. 95594'], dtype=object)

In [18]:
# услуга
applications['Услуга'].unique()

array(['ИТ-АРМ', 'ИТ-Система КЦ', 'ИТ-Учетная запись домена', 'ИТ-СКС',
       'ИТ-Оргтехника',
       'ИТ-Поддержка процессов информационной безопасности',
       'ИТ-Интернет', 'ИТ-Система отображения информации',
       'ИТ-Поддержка систем информационной безопасности',
       'ИТ-VIP-пользователь', 'ИТ-Оборудование ЛВС', 'ИТ-ВКС',
       'ИТ-Документооборот', 'ИТ-Доступа к файловым сетевым ресурсам',
       'ВН-1-2 Внешние услуги', 'ИТ-Электронная почта',
       'ИТ-Система управления инженерными данными',
       'ИТ-Поддержка серверов (программная)',
       'ИТ-Система управления строительством',
       'ИТ-АРМ с удаленным доступом, VDI', 'ВН-3-1-Услуги ОИКТ',
       'ИТ-Аналитическая система общего назначения',
       '1-я линия поддержки', 'БК - Информационные системы',
       'ИТ-Система видеонаблюдения', 'ИТ-Поддержка СИРИУС-СБ',
       'ИТ-DigitalAtom', 'ИТ-Диспетчерская служба',
       'ИТ-Система электроснабжения',
       'ИТ-Поддержка серверов в части программного обеспечения',
       'ИТ-Система часофикации', 'ИТ-Корпоративные справочники НСИ',
       'ИТ-Система управления сбытом', 'ИТ-Порталы и сайты',
       'ИТ-ИТ-актив', 'ПР-0-0-Проекты', 'ИТ-Мониторинг',
       'Управление конфигурациями (CMDB)', 'ИТ-Система клиент-банк',
       'ИТ-Системы связи и оповещений', 'ИТ-Сбор и обработка отчетности',
       'КОС-7-1-Внутренние работы', 'ИТ-Телефония'], dtype=object)

In [19]:
# вид запроса
applications['Вид запроса'].unique()

array(['4. Настройка / обновление ПО', 'Запрос на обслуживание',
       'Настройка / обновление ПО', 'Техническое обслуживание ПК',
       'Настройка клиента электронной почты',
       '5. Установка / переустановка Windows',
       'Установка драйвера принтера, сканера, МФУ',
       'Перенастройка ПК на нового пользователя',
       '2. Установка дополнительного программного обеспечения',
       '1. Установка стандартного программного обеспечения',
       'Запрос на обслуживание (ИТ-6 ИТ-Поддержка процессов ИБ)',
       'Обслуживание  дополнительного программного обеспечения',
       'Установить / подключить ПК на рабочем месте пользователя',
       'Установка дополнительного программного обеспечения',
       'Установка стандартного программного обеспечения',
       'Замена / заправка картриджа',
       '3. Установка драйвера принтера, сканера, МФУ',
       'Доступ к папке (сетевому ресурсу)',
       'Доступ в группу Active Directory (предоставление / изменение / блокировка)',
       'Запрос на обслуживание_',
       'Копирование данных (ПК / Сеть / Интернет)', 'Консультация',
       'Консультирование пользователя Заказчика по работе в системе удаленного доступа',
       'Установка стандартного ПО',
       'Корректировка данных пользователя в AD',
       'Настройка АРМ для удаленной работы (Композитный запрос)',
       'Первичная классификация', 'Установка ИС на АРМ',
       'Настройка АРМ для удаленной работы ЛенАЭС',
       'Регистрация в ЛВС нового пользователя',
       'Доступ (предоставление | изменение | блокировка)',
       'Поддержка и настройка АРМ VDI', 'Актуализация реестра ОО',
       'Входной контроль ПК', 'Обслуживание АРМ',
       'Повторная классификация',
       'Установить / подключить ПК на рабочем месте',
       'Обновление и изменение КЕ', 'Полугодовое ТО',
       'Предоставление удаленного доступа VDI (композит)',
       'Заявка к расходному договору', 'Запрос на изменение'],
      dtype=object)

In [20]:
# ============================================
# Шаг 2. Анонимизация РАСПОЛОЖЕНИЯ
# ============================================

print("\n" + "="*60)
print("ШАГ 2. АНОНИМИЗАЦИЯ РАСПОЛОЖЕНИЯ")
print("="*60)

# --- 2.1 Анализируем уникальные значения ДО замены ---
original_locations = applications['Расположение'].dropna().unique()
num_locations = len(original_locations)

print(f"\nДО замены:")
print(f"  Уникальных объектов: {num_locations}")
print(f"  Примеры реальных названий: {original_locations[:5]}")

# --- 2.2 Создаем синтетические названия для атомных станций и объектов ---
# Генерируем 18 вымышленных названий
synthetic_locations = [
    # Атомные станции
    "АЭС-1 (Северная)",
    "АЭС-2 (Западная)",
    "АЭС-3 (Восточная)",
    "АЭС-4 (Южная)",
    "АЭС-5 (Центральная)",
    "АЭС-6 (Прибрежная)",
    # Объекты и площадки
    "Промплощадка Альфа",
    "Промплощадка Бета",
    "Хранилище отработанного топлива №1",
    "Хранилище отработанного топлива №2",
    "Учебно-тренировочный центр",
    "Лабораторный корпус",
    "Административно-бытовой корпус",
    "Здание управления (ЗУ-1)",
    "Здание управления (ЗУ-2)",
    "Резервный пункт управления",
    "Складское хозяйство",
    "Турбинный цех"
]

# Проверяем, что количество совпадает
print(f"\nСгенерировано синтетических названий: {len(synthetic_locations)}")
print(f"  Примеры новых названий: {synthetic_locations[:5]}")

if len(synthetic_locations) != num_locations:
    print(f"  ВНИМАНИЕ: Количество не совпадает! Нужно {num_locations}, создано {len(synthetic_locations)}")
    # Дополняем если нужно
    while len(synthetic_locations) < num_locations:
        synthetic_locations.append(f"Объект Special-{len(synthetic_locations)+1}")
else:
    print(f"  ✓ Количество совпадает: {num_locations}")

# --- 2.3 Создаем маппинг и применяем замену ---
location_mapping = dict(zip(original_locations, synthetic_locations))

print("\nПримеры маппинга (первые 5):")
for i, (orig, synth) in enumerate(list(location_mapping.items())[:5]):
    print(f"  {orig} -> {synth}")

# Применяем замену
applications_anon['Расположение'] = applications['Расположение'].map(location_mapping).fillna(applications['Расположение'])

# --- 2.4 Проверка ---
new_locations = applications_anon['Расположение'].dropna().unique()
print(f"\nПОСЛЕ замены:")
print(f"  Уникальных объектов: {len(new_locations)}")
print(f"  Примеры новых названий: {new_locations[:5]}")
print(f"  Совпадает ли количество? {'✓ ДА' if len(new_locations) == num_locations else '✗ НЕТ'}")

============================================================
ШАГ 2. АНОНИМИЗАЦИЯ РАСПОЛОЖЕНИЯ
============================================================

ДО замены:
  Уникальных объектов: 18
  Примеры реальных названий: ['ПАТЭС Спб' 'Ленинградская АЭС' 'Ленинградская АЭС-2' 'ЦА Москва'
 'ЛенАЭС Ленинградская область']

Сгенерировано синтетических названий: 18
  Примеры новых названий: ['АЭС-1 (Северная)', 'АЭС-2 (Западная)', 'АЭС-3 (Восточная)', 'АЭС-4 (Южная)', 'АЭС-5 (Центральная)']
  ✓ Количество совпадает: 18

Примеры маппинга (первые 5):
  ПАТЭС Спб -> АЭС-1 (Северная)
  Ленинградская АЭС -> АЭС-2 (Западная)
  Ленинградская АЭС-2 -> АЭС-3 (Восточная)
  ЦА Москва -> АЭС-4 (Южная)
  ЛенАЭС Ленинградская область -> АЭС-5 (Центральная)

ПОСЛЕ замены:
  Уникальных объектов: 18
  Примеры новых названий: ['АЭС-1 (Северная)' 'АЭС-2 (Западная)' 'АЭС-3 (Восточная)' 'АЭС-4 (Южная)'
 'АЭС-5 (Центральная)']
  Совпадает ли количество? ✓ ДА

In [21]:
# ============================================
# Шаг 3. АНОНИМИЗАЦИЯ УСЛУГ (ПРАВИЛЬНАЯ КАТЕГОРИЗАЦИЯ)
# ============================================

print("\n" + "="*60)
print("ШАГ 3. АНОНИМИЗАЦИЯ УСЛУГ (С КАТЕГОРИЯМИ)")
print("="*60)

# --- 3.1 Оригинальные услуги ---
original_services = applications['Услуга'].dropna().unique()
print(f"\nОригинальных услуг: {len(original_services)}")

# --- 3.2 ПРАВИЛЬНЫЙ маппинг по категориям ---
service_mapping = {
    # РАБОЧИЕ СТАНЦИИ И АРМ (должны стать рабочими станциями)
    'ИТ-АРМ': 'Рабочая станция (стандарт)',
    'ИТ-VIP-пользователь': 'Рабочая станция (повышенной защищенности)',
    'ИТ-АРМ с удаленным доступом, VDI': 'Тонкий клиент / VDI',
    '1-я линия поддержки': 'Рабочая станция оператора',
    'ИТ-Система КЦ': 'Рабочая станция (КЦ)',  # Коллективный центр - тоже рабочая станция
    
    # СЕТЕВОЕ ОБОРУДОВАНИЕ
    'ИТ-СКС': 'Сетевое оборудование (пассивное)',
    'ИТ-Оборудование ЛВС': 'Сетевое оборудование (активное)',
    'ИТ-Интернет': 'Доступ в интернет (сетевое)',
    
    # СЕРВЕРЫ
    'ИТ-Поддержка серверов (программная)': 'Серверное ПО',
    'ИТ-Поддержка серверов в части программного обеспечения': 'Серверная инфраструктура',
    'ИТ-Мониторинг': 'Система мониторинга серверов',
    
    # ОРГТЕХНИКА
    'ИТ-Оргтехника': 'Оргтехника (принтеры/МФУ)',
    
    # СИСТЕМЫ БЕЗОПАСНОСТИ
    'ИТ-Поддержка процессов информационной безопасности': 'СЗИ (антивирусы/шифрование)',
    'ИТ-Поддержка систем информационной безопасности': 'Специализированные СЗИ',
    'ИТ-Поддержка СИРИУС-СБ': 'Система безопасности СИРИУС',
    
    # СПЕЦИАЛИЗИРОВАННЫЕ СИСТЕМЫ
    'ИТ-Система отображения информации': 'Система отображения (табло/мониторы)',
    'ИТ-Система видеонаблюдения': 'Система видеонаблюдения',
    'ИТ-Система электроснабжения': 'СКУД и электроснабжение',
    'ИТ-Система часофикации': 'Система единого времени',
    'ИТ-Система управления инженерными данными': 'Инженерные САПР',
    'ИТ-Система управления строительством': 'Строительные информационные системы',
    'ИТ-Система управления сбытом': 'Сбытовые информационные системы',
    'ИТ-Аналитическая система общего назначения': 'BI-системы',
    'ИТ-Диспетчерская служба': 'Диспетчерские системы',
    
    # ПОЧТА И ДОКУМЕНТЫ
    'ИТ-Электронная почта': 'Корпоративная почта',
    'ИТ-Документооборот': 'СЭД',
    
    # УЧЕТНЫЕ ЗАПИСИ
    'ИТ-Учетная запись домена': 'Учетные записи (AD)',
    'ИТ-Доступа к файловым сетевым ресурсам': 'Файловые ресурсы и доступы',
    
    # СВЯЗЬ
    'ИТ-ВКС': 'Видео-конференц-связь',
    'ИТ-Телефония': 'IP-телефония',
    'ИТ-Системы связи и оповещений': 'Системы оповещения',
    
    # ОСТАЛЬНОЕ (подберем категории)
    'ИТ-Порталы и сайты': 'Корпоративный портал',
    'ИТ-Корпоративные справочники НСИ': 'НСИ и справочники',
    'ИТ-Сбор и обработка отчетности': 'Отчетные системы',
    'ИТ-DigitalAtom': 'Цифровая платформа',
    'ИТ-ИТ-актив': 'Учет ИТ-активов',
    'ИТ-Система клиент-банк': 'Финансовые системы',
    
    # ВНЕШНИЕ УСЛУГИ
    'ВН-1-2 Внешние услуги': 'Внешние ИТ-услуги',
    'ВН-3-1-Услуги ОИКТ': 'Услуги ОИКТ',
    'ПР-0-0-Проекты': 'Проектная деятельность',
    'БК - Информационные системы': 'Банковские информационные системы',
    'КОС-7-1-Внутренние работы': 'Внутренние работы'
}

# Проверяем, все ли оригинальные услуги попали в маппинг
missing = [s for s in original_services if s not in service_mapping]
if missing:
    print(f"\nПропущены услуги: {missing}")
    # Добавляем пропущенные
    for s in missing:
        service_mapping[s] = f"ИТ-услуга ({s.split('-')[-1]})"

print(f"\nМаппинг создан для {len(service_mapping)} услуг")

# Группируем по категориям для проверки
categories = {}
for orig, synth in service_mapping.items():
    if 'Рабочая станция' in synth:
        cat = 'Рабочие станции'
    elif 'Сетев' in synth:
        cat = 'Сети'
    elif 'Сервер' in synth:
        cat = 'Серверы'
    elif 'Оргтехника' in synth:
        cat = 'Оргтехника'
    elif 'СЗИ' in synth or 'безопасн' in synth:
        cat = 'Безопасность'
    elif 'видео' in synth.lower() or 'отображ' in synth.lower():
        cat = 'Спецсистемы'
    elif 'почт' in synth.lower() or 'сэд' in synth.lower():
        cat = 'Документооборот'
    else:
        cat = 'Прочее'
    
    if cat not in categories:
        categories[cat] = []
    categories[cat].append((orig, synth))

print("\nРаспределение по категориям:")
for cat, items in categories.items():
    print(f"  {cat}: {len(items)} услуг")
    # Покажем примеры
    for orig, synth in items[:2]:
        print(f"    {orig} -> {synth}")
    if len(items) > 2:
        print(f"    ...")

# Применяем маппинг
service_col = None
for col in applications_anon.columns:
    if 'Услуга' in col:
        service_col = col
        break

if service_col:
    applications_anon[service_col] = applications[service_col].map(service_mapping).fillna(applications[service_col])
    print(f"\n✓ Замена применена")
    
    # Покажем результат
    print("\nИтоговые услуги (первые 15):")
    for service in sorted(applications_anon[service_col].unique())[:15]:
        print(f"  {service}")

============================================================
ШАГ 3. АНОНИМИЗАЦИЯ УСЛУГ (С КАТЕГОРИЯМИ)
============================================================

Оригинальных услуг: 43

Пропущены услуги: ['Управление конфигурациями (CMDB)']

Маппинг создан для 43 услуг

Распределение по категориям:
  Рабочие станции: 4 услуг
    ИТ-АРМ -> Рабочая станция (стандарт)
    ИТ-VIP-пользователь -> Рабочая станция (повышенной защищенности)
    ...
  Прочее: 26 услуг
    ИТ-АРМ с удаленным доступом, VDI -> Тонкий клиент / VDI
    ИТ-Интернет -> Доступ в интернет (сетевое)
    ...
  Сети: 2 услуг
    ИТ-СКС -> Сетевое оборудование (пассивное)
    ИТ-Оборудование ЛВС -> Сетевое оборудование (активное)
  Серверы: 2 услуг
    ИТ-Поддержка серверов (программная) -> Серверное ПО
    ИТ-Поддержка серверов в части программного обеспечения -> Серверная инфраструктура
  Оргтехника: 1 услуг
    ИТ-Оргтехника -> Оргтехника (принтеры/МФУ)
  Безопасность: 3 услуг
    ИТ-Поддержка процессов информационной безопасности -> СЗИ (антивирусы/шифрование)
    ИТ-Поддержка систем информационной безопасности -> Специализированные СЗИ
    ...
  Спецсистемы: 3 услуг
    ИТ-Система отображения информации -> Система отображения (табло/мониторы)
    ИТ-Система видеонаблюдения -> Система видеонаблюдения
    ...
  Документооборот: 2 услуг
    ИТ-Электронная почта -> Корпоративная почта
    ИТ-Документооборот -> СЭД

✓ Замена применена

Итоговые услуги (первые 15):
  BI-системы
  IP-телефония
  Банковские информационные системы
  Видео-конференц-связь
  Внешние ИТ-услуги
  Внутренние работы
  Диспетчерские системы
  Доступ в интернет (сетевое)
  ИТ-услуга (Управление конфигурациями (CMDB))
  Инженерные САПР
  Корпоративная почта
  Корпоративный портал
  НСИ и справочники
  Оргтехника (принтеры/МФУ)
  Отчетные системы

In [24]:
# ============================================
# Шаг 4. ГЕНЕРАЦИЯ ОПИСАНИЙ ДЛЯ ВСЕХ КАТЕГОРИЙ
# ============================================
import random

print("\n" + "="*60)
print("ШАГ 4. ГЕНЕРАЦИЯ ОПИСАНИЙ (ВСЕ КАТЕГОРИИ)")
print("="*60)

# --- Определяем категории услуг по их названиям ---
def get_detailed_category(service_name):
    """Точное определение категории услуги"""
    s = str(service_name).lower()
    
    if 'рабочая станция' in s or 'арм' in s or 'тонкий клиент' in s or 'vdi' in s:
        return 'workstation'
    elif 'сетев' in s or 'лвс' in s or 'скс' in s or 'доступ в интернет' in s:
        return 'network'
    elif 'сервер' in s or 'мониторинг' in s:
        return 'server'
    elif 'оргтехника' in s or 'принтер' in s or 'мфу' in s:
        return 'printers'
    elif 'сзи' in s or 'безопасн' in s or 'антивирус' in s or 'сириус' in s:
        return 'security'
    elif 'видеонаблюд' in s or 'отображен' in s or 'часофикац' in s or 'электроснабж' in s:
        return 'special'
    elif 'почт' in s or 'сэд' in s or 'документооборот' in s:
        return 'docflow'
    elif 'вкс' in s or 'телефон' in s or 'связи' in s:
        return 'communication'
    elif 'учетн' in s or 'домен' in s or 'файлов' in s:
        return 'access'
    else:
        return 'other'

# --- ШАБЛОНЫ ДЛЯ КАЖДОЙ КАТЕГОРИИ ---
templates_by_category = {
    'workstation': [
        "На рабочей станции {problem}. Требуется помощь.",
        "Не загружается {os} на ПК пользователя.",
        "После обновления {software} перестал работать {function}.",
        "Прошу установить {software} на компьютер в {location}.",
        "Синий экран при запуске. Ошибка: {error_code}",
        "Зависает {software} при работе с документами."
    ],
    
    'network': [
        "Пропал интернет в {location}. Не пингуется {resource}.",
        "Не работает {equipment} в {location}. Нет связи с серверами.",
        "Требуется настроить доступ к {resource} из {location}.",
        "Медленно работает сеть в {location}. Скорость упала.",
        "Не подключается к Wi-Fi в {location}. Точка доступа не видна."
    ],
    
    'server': [
        "Не отвечает сервер {server_name}. Ошибка подключения.",
        "Высокая нагрузка на CPU сервера {server_name}.",
        "Сбой службы на сервере. Требуется перезапуск.",
        "Закончилось место на диске сервера {server_name}.",
        "Ошибка резервного копирования на сервере {server_name}."
    ],
    
    'printers': [
        "Не печатает {printer_model} в {location}. Ошибка подачи бумаги.",
        "Закончился тонер в принтере. Требуется замена картриджа.",
        "Застряла бумага в МФУ. Нужна помощь.",
        "Сканер не видит документы. Ошибка подключения.",
        "Принтер выдает ошибку {error_code}. Требуется диагностика."
    ],
    
    'security': [
        "Антивирус заблокировал {software}. Требуется исключение.",
        "Сработала сигнализация СЗИ на рабочей станции.",
        "Не открывается {resource}. Требуются права доступа.",
        "Истек срок действия сертификата у пользователя.",
        "Обнаружена подозрительная активность в системе."
    ],
    
    'special': [
        "Не работает камера {camera_id} в {location}. Нет сигнала.",
        "Сбой в системе отображения информации. Не обновляются данные.",
        "Рассинхронизация времени на оборудовании.",
        "Нет данных с датчиков в {location}. Требуется проверка.",
        "Ошибка отображения на табло коллективного пользования."
    ],
    
    'docflow': [
        "Не отправляется письмо с ошибкой {error_code}.",
        "Не приходит почта на ящик пользователя.",
        "Зависает СЭД при открытии документа.",
        "Требуется настроить шаблон документа в СЭД.",
        "Ошибка согласования документа в системе."
    ],
    
    'communication': [
        "Нет звука в {location} при ВКС.",
        "Плохая слышимость по телефону. Шумы.",
        "Не работает микрофон в переговорной {location}.",
        "Сбрасывается соединение при ВКС.",
        "Телефон не регистрируется в сети. Ошибка авторизации."
    ],
    
    'access': [
        "Не могу зайти в {system} под учетной записью.",
        "Требуется создать учетную запись для нового сотрудника.",
        "Нет доступа к папке {folder} на сервере.",
        "Истек срок действия пароля. Прошу разблокировать.",
        "Учетная запись заблокирована после неудачных попыток."
    ],
    
    'other': [
        "Требуется обслуживание по заявке.",
        "Заявка на выполнение работ.",
        "Прошу помочь с настройкой."
    ]
}

# --- Словари для подстановки ---
values = {
    'problem': ['зависает', 'тормозит', 'выдает ошибку', 'не включается', 'перезагружается'],
    'os': ['Windows 10', 'Windows 11', 'Astra Linux', 'ALT Linux', 'РЕД ОС'],
    'software': ['Microsoft Office', 'LibreOffice', '1С:Предприятие', 'САПР', 'СЭД'],
    'function': ['печать', 'сохранение', 'отправка почты', 'экспорт данных', 'открытие документов'],
    'error_code': ['0x80070005', '0x80004005', '0x80070002', '0x80070570'],
    'equipment': ['коммутатор', 'маршрутизатор', 'точка доступа', 'медиаконвертер'],
    'resource': ['сервер', 'базу данных', 'корпоративный портал', '1С', 'файловый ресурс'],
    'server_name': ['SRV-DC01', 'SRV-FS02', 'SRV-SQL01', 'SRV-APP01', 'SRV-BACKUP'],
    'service': ['служба DNS', 'служба DHCP', 'Active Directory', 'служба печати'],
    'printer_model': ['HP LaserJet', 'Xerox', 'Kyocera', 'Canon', 'Brother'],
    'camera_id': [f'CAM-{i:03d}' for i in range(1, 11)],
    'city': ['Москва', 'Санкт-Петербург', 'Воронеж', 'Саратов'],
    'phone': ['101-12', '102-34', '103-56', '104-78'],
    'folder': ['Отчеты', 'Документация', 'Проекты', 'Сметы', 'Общая'],
    'system': ['Active Directory', '1С', 'СЭД', 'почтовую систему', 'корпоративный портал']
}

# --- ОПРЕДЕЛЯЕМ ВСЕ НУЖНЫЕ КОЛОНКИ ---
print("\nОпределяем колонки...")

service_col = None
request_col = None
description_col = None
location_col = None

for col in applications_anon.columns:
    if 'Услуга' in col:
        service_col = col
        print(f"  Найдена колонка услуги: '{service_col}'")
    elif 'Вид запроса' in col:
        request_col = col
        print(f"  Найдена колонка вида запроса: '{request_col}'")
    elif 'Описание' in col:
        description_col = col
        print(f"  Найдена колонка описания: '{description_col}'")
    elif 'Расположение' in col:
        location_col = col
        print(f"  Найдена колонка расположения: '{location_col}'")

# Проверяем, что все нужные колонки найдены
if not service_col:
    raise ValueError("Не найдена колонка с услугой!")
if not request_col:
    raise ValueError("Не найдена колонка с видом запроса!")
if not description_col:
    raise ValueError("Не найдена колонка с описанием!")

print("\n✓ Все необходимые колонки найдены")

# --- Генерация описаний ---
print("\nГенерируем описания...")

new_descriptions = []
category_stats = {}

for idx, row in applications_anon.iterrows():
    service = row[service_col]
    req_type = row[request_col]
    location = row.get(location_col, 'офис') if location_col else 'офис'
    
    # Определяем категорию
    category = get_detailed_category(service)
    category_stats[category] = category_stats.get(category, 0) + 1
    
    # Выбираем шаблон
    templates = templates_by_category.get(category, templates_by_category['other'])
    template = random.choice(templates)
    
    # Подготавливаем переменные
    template_vars = {}
    for key in values.keys():
        template_vars[key] = random.choice(values[key])
    template_vars['location'] = location
    template_vars['request_type'] = req_type
    
    # Формируем описание
    try:
        description = template.format(**template_vars)
    except KeyError as e:
        description = f"Заявка по услуге {service}. Тип: {req_type}"
    
    # Добавляем вежливость
    if random.random() > 0.5:
        description = "Добрый день! " + description[0].lower() + description[1:]
    
    new_descriptions.append(description)

# Применяем
applications_anon[description_col] = new_descriptions

# --- Статистика ---
print("\nСтатистика по категориям:")
total = len(applications_anon)
for cat, count in sorted(category_stats.items()):
    print(f"  {cat}: {count} заявок ({count/total*100:.1f}%)")

print(f"\nВсего обработано: {total} заявок")

# Показываем примеры
print("\nПримеры сгенерированных описаний по категориям:")
for category in ['workstation', 'network', 'server', 'printers', 'security', 'special', 'docflow', 'communication', 'access']:
    examples = []
    for idx, row in applications_anon.iterrows():
        if get_detailed_category(row[service_col]) == category and len(examples) < 2:
            examples.append(row[description_col])
    
    if examples:
        print(f"\n{category.upper()}:")
        for ex in examples:
            print(f"  - {ex}")

============================================================
ШАГ 4. ГЕНЕРАЦИЯ ОПИСАНИЙ (ВСЕ КАТЕГОРИИ)
============================================================

Определяем колонки...
  Найдена колонка расположения: 'Расположение'
  Найдена колонка описания: 'Описание'
  Найдена колонка услуги: 'Услуга'
  Найдена колонка вида запроса: 'Вид запроса'

✓ Все необходимые колонки найдены

Генерируем описания...

Статистика по категориям:
  access: 362 заявок (1.9%)
  communication: 1 заявок (0.0%)
  docflow: 107 заявок (0.6%)
  network: 192 заявок (1.0%)
  other: 399 заявок (2.1%)
  printers: 62 заявок (0.3%)
  security: 283 заявок (1.5%)
  server: 104 заявок (0.5%)
  special: 32 заявок (0.2%)
  workstation: 17450 заявок (91.9%)

Всего обработано: 18992 заявок

Примеры сгенерированных описаний по категориям:

WORKSTATION:
  - Добрый день! синий экран при запуске. Ошибка: 0x80070570
  - Добрый день! прошу установить СЭД на компьютер в АЭС-2 (Западная).

NETWORK:
  - Добрый день! не работает медиаконвертер в АЭС-2 (Западная). Нет связи с серверами.
  - Добрый день! медленно работает сеть в АЭС-2 (Западная). Скорость упала.

SERVER:
  - Добрый день! закончилось место на диске сервера SRV-SQL01.
  - Высокая нагрузка на CPU сервера SRV-DC01.

PRINTERS:
  - Добрый день! закончился тонер в принтере. Требуется замена картриджа.
  - Добрый день! не печатает Kyocera в АЭС-2 (Западная). Ошибка подачи бумаги.

SECURITY:
  - Добрый день! истек срок действия сертификата у пользователя.
  - Не открывается 1С. Требуются права доступа.

SPECIAL:
  - Ошибка отображения на табло коллективного пользования.
  - Ошибка отображения на табло коллективного пользования.

DOCFLOW:
  - Зависает СЭД при открытии документа.
  - Не приходит почта на ящик пользователя.

COMMUNICATION:
  - Добрый день! не работает микрофон в переговорной АЭС-2 (Западная).

ACCESS:
  - Добрый день! требуется создать учетную запись для нового сотрудника.
  - Добрый день! истек срок действия пароля. Прошу разблокировать.

In [26]:
# ============================================
# Шаг 5. ФИНАЛЬНАЯ ПРОВЕРКА ДАТАСЕТА
# ============================================

print("\n" + "="*60)
print("ШАГ 5. ФИНАЛЬНАЯ ПРОВЕРКА ДАТАСЕТА")
print("="*60)

import pandas as pd
import numpy as np

# --- 5.1 Проверка структуры ---
print("\n1. СТРУКТУРА ДАТАСЕТА:")
print(f"   Всего записей: {len(applications_anon)}")
print(f"   Всего колонок: {len(applications_anon.columns)}")
print(f"\n   Колонки в датасете:")
for col in applications_anon.columns:
    print(f"   - {col}")

# --- 5.2 Проверка анонимизации ---
print("\n2. ПРОВЕРКА АНОНИМИЗАЦИИ:")

# Проверяем, что нет оригинальных названий станций
original_locations_check = ['АЭС', 'ЛенАЭС', 'Смоленская', 'Калининская', 'Балаковская', 'Нововоронежская']
found_originals = []

for loc in original_locations_check:
    if applications_anon['Расположение'].astype(str).str.contains(loc, na=False).any():
        found_originals.append(loc)

if found_originals:
    print(f"   ⚠️ ВНИМАНИЕ: Найдены оригинальные названия: {found_originals}")
else:
    print("   ✓ Расположение: оригинальные названия не найдены")

# Проверяем, что нет оригинальных услуг
original_services_check = ['ИТ-АРМ', 'ИТ-СКС', 'ИТ-ВКС', '1-я линия']
found_services = []

for serv in original_services_check:
    if applications_anon[service_col].astype(str).str.contains(serv, na=False).any():
        found_services.append(serv)

if found_services:
    print(f"   ⚠️ ВНИМАНИЕ: Найдены оригинальные услуги: {found_services}")
else:
    print("   ✓ Услуги: оригинальные названия не найдены")

# --- 5.3 Статистика по колонкам ---
print("\n3. СТАТИСТИКА ПО КЛЮЧЕВЫМ КОЛОНКАМ:")

# Расположение
print(f"\n   Расположение:")
print(f"     Уникальных объектов: {applications_anon['Расположение'].nunique()}")
print(f"     Примеры: {applications_anon['Расположение'].unique()[:5]}")

# Услуги
print(f"\n   Услуги:")
print(f"     Уникальных услуг: {applications_anon[service_col].nunique()}")
print(f"     Топ-5 услуг по количеству заявок:")
service_counts = applications_anon[service_col].value_counts().head(5)
for serv, count in service_counts.items():
    print(f"       {serv}: {count} заявок ({count/len(applications_anon)*100:.1f}%)")

# Виды запросов
print(f"\n   Виды запросов:")
print(f"     Уникальных видов: {applications_anon[request_col].nunique()}")
print(f"     Топ-5 видов запросов:")
request_counts = applications_anon[request_col].value_counts().head(5)
for req, count in request_counts.items():
    print(f"       {req}: {count} заявок")

# Приоритеты
print(f"\n   Приоритеты:")
if 'Приоритет' in applications_anon.columns:
    priority_counts = applications_anon['Приоритет'].value_counts()
    for pri, count in priority_counts.items():
        print(f"     {pri}: {count} заявок ({count/len(applications_anon)*100:.1f}%)")

# Просрочки SLA
print(f"\n   SLA (Просрочен):")
if 'Просрочен' in applications_anon.columns:
    overdue_counts = applications_anon['Просрочен'].value_counts()
    for status, count in overdue_counts.items():
        status_text = 'Просрочено' if status else 'В срок'
        print(f"     {status_text}: {count} заявок ({count/len(applications_anon)*100:.1f}%)")

# --- 5.4 Проверка описаний ---
print("\n4. ПРОВЕРКА ОПИСАНИЙ:")

# Проверяем длину описаний
desc_lengths = applications_anon[description_col].str.len()
print(f"   Средняя длина описания: {desc_lengths.mean():.0f} символов")
print(f"   Минимальная длина: {desc_lengths.min()} символов")
print(f"   Максимальная длина: {desc_lengths.max()} символов")

# Проверяем наличие ключевых слов
keywords = ['ошибка', 'сбой', 'не работает', 'зависает', 'установить', 'настроить', 'доступ']
print(f"\n   Частота ключевых слов в описаниях:")
for kw in keywords:
    count = applications_anon[description_col].str.contains(kw, case=False, na=False).sum()
    print(f"     '{kw}': {count} раз ({count/len(applications_anon)*100:.1f}%)")

# --- 5.5 Примеры итоговых данных ---
print("\n5. ПРИМЕРЫ ИТОГОВЫХ ДАННЫХ (первые 5 строк):")
print("\n" + "="*100)
for i in range(min(5, len(applications_anon))):
    print(f"\nЗаявка #{i+1}:")
    print(f"  Расположение: {applications_anon.iloc[i]['Расположение']}")
    print(f"  Услуга: {applications_anon.iloc[i][service_col]}")
    print(f"  Вид запроса: {applications_anon.iloc[i][request_col]}")
    print(f"  Приоритет: {applications_anon.iloc[i]['Приоритет'] if 'Приоритет' in applications_anon.columns else 'Н/Д'}")
    print(f"  Просрочена: {applications_anon.iloc[i]['Просрочен'] if 'Просрочен' in applications_anon.columns else 'Н/Д'}")
    print(f"  Описание: {applications_anon.iloc[i][description_col][:150]}...")

# --- 5.6 Сохранение результатов ---
print("\n6. СОХРАНЕНИЕ РЕЗУЛЬТАТОВ:")

# Сохраняем основной датасет
output_file = 'support_tickets_final_anonymized.csv'
applications_anon.to_csv(output_file, index=False, encoding='utf-8-sig')
print(f"   ✓ Основной датасет сохранен: {output_file}")

# Сохраняем краткую статистику
stats = {
    'Всего заявок': len(applications_anon),
    'Уникальных объектов': applications_anon['Расположение'].nunique(),
    'Уникальных услуг': applications_anon[service_col].nunique(),
    'Уникальных видов запросов': applications_anon[request_col].nunique(),
    'Средняя длина описания': desc_lengths.mean(),
    'Процент просрочек': (applications_anon['Просрочен'].sum() / len(applications_anon) * 100) if 'Просрочен' in applications_anon.columns else 0
}

stats_df = pd.DataFrame([stats])
stats_df.to_csv('dataset_statistics.csv', index=False, encoding='utf-8-sig')
print(f"   ✓ Статистика сохранена: dataset_statistics.csv")

# --- 5.7 Финальное сообщение ---
print("\n" + "="*60)
print("🎉 ФИНАЛИЗАЦИЯ ЗАВЕРШЕНА")
print("="*60)
print("\nВаш датасет полностью готов для портфолио!")
print("Теперь вы можете использовать его для:")
print("  • Анализа метрик SLA")
print("  • Построения дашбордов в Power BI / Metabase")
print("  • Выявления топ-5 причин сбоев")
print("  • Анализа эффективности импортозамещения")
print("  • И любых других задач из вашего резюме")
print("\n✅ Данные анонимизированы и готовы к публичной демонстрации")

============================================================
ШАГ 5. ФИНАЛЬНАЯ ПРОВЕРКА ДАТАСЕТА
============================================================

1. СТРУКТУРА ДАТАСЕТА:
   Всего записей: 18992
   Всего колонок: 16

   Колонки в датасете:
   - Дата/время регистрации
   - Крайний срок обработки
   - Фактическое время выполнения
   - Плановое время выполнения
   - Приоритет
   - Просрочен
   - Результат работ
   - Получатель услуг
   - Инициатор
   - Кем решен (сотрудник)
   - Расположение
   - Описание
   - Услуга
   - Компонент услуги
   - Вид запроса
   - Площадка обслуживания пользователя

2. ПРОВЕРКА АНОНИМИЗАЦИИ:
   ⚠️ ВНИМАНИЕ: Найдены оригинальные названия: ['АЭС']
   ✓ Услуги: оригинальные названия не найдены

3. СТАТИСТИКА ПО КЛЮЧЕВЫМ КОЛОНКАМ:

   Расположение:
     Уникальных объектов: 18
     Примеры: ['АЭС-1 (Северная)' 'АЭС-2 (Западная)' 'АЭС-3 (Восточная)' 'АЭС-4 (Южная)'
 'АЭС-5 (Центральная)']

   Услуги:
     Уникальных услуг: 43
     Топ-5 услуг по количеству заявок:
       Рабочая станция (стандарт): 17203 заявок (90.6%)
       Учетные записи (AD): 265 заявок (1.4%)
       Специализированные СЗИ: 157 заявок (0.8%)
       Услуги ОИКТ: 152 заявок (0.8%)
       Тонкий клиент / VDI: 145 заявок (0.8%)

   Виды запросов:
     Уникальных видов: 42
     Топ-5 видов запросов:
       Запрос на обслуживание: 12578 заявок
       Установка драйвера принтера, сканера, МФУ: 2183 заявок
       Настройка клиента электронной почты: 839 заявок
       Перенастройка ПК на нового пользователя: 692 заявок
       Обслуживание  дополнительного программного обеспечения: 625 заявок

   Приоритеты:
     (4) Низкий: 13756 заявок (72.4%)
     (3) Средний: 4141 заявок (21.8%)
     (1) Наивысший: 778 заявок (4.1%)
     (2) Высокий: 317 заявок (1.7%)

   SLA (Просрочен):
     Просрочено: 18888 заявок (99.5%)
     Просрочено: 104 заявок (0.5%)

4. ПРОВЕРКА ОПИСАНИЙ:
   Средняя длина описания: 56 символов
   Минимальная длина: 26 символов
   Максимальная длина: 92 символов

   Частота ключевых слов в описаниях:
     'ошибка': 3038 раз (16.0%)
     'сбой': 36 раз (0.2%)
     'не работает': 44 раз (0.2%)
     'зависает': 3419 раз (18.0%)
     'установить': 2883 раз (15.2%)
     'настроить': 64 раз (0.3%)
     'доступ': 225 раз (1.2%)

5. ПРИМЕРЫ ИТОГОВЫХ ДАННЫХ (первые 5 строк):

====================================================================================================

Заявка #1:
  Расположение: АЭС-1 (Северная)
  Услуга: Рабочая станция (стандарт)
  Вид запроса: 4. Настройка / обновление ПО
  Приоритет: (4) Низкий
  Просрочена: не просрочен
  Описание: Добрый день! синий экран при запуске. Ошибка: 0x80070570...

Заявка #2:
  Расположение: АЭС-2 (Западная)
  Услуга: Рабочая станция (стандарт)
  Вид запроса: Запрос на обслуживание
  Приоритет: (4) Низкий
  Просрочена: не просрочен
  Описание: Добрый день! прошу установить СЭД на компьютер в АЭС-2 (Западная)....

Заявка #3:
  Расположение: АЭС-3 (Восточная)
  Услуга: Рабочая станция (стандарт)
  Вид запроса: Настройка / обновление ПО
  Приоритет: (4) Низкий
  Просрочена: не просрочен
  Описание: Добрый день! зависает 1С:Предприятие при работе с документами....

Заявка #4:
  Расположение: АЭС-1 (Северная)
  Услуга: Рабочая станция (стандарт)
  Вид запроса: 4. Настройка / обновление ПО
  Приоритет: (4) Низкий
  Просрочена: не просрочен
  Описание: Добрый день! после обновления СЭД перестал работать сохранение....

Заявка #5:
  Расположение: АЭС-4 (Южная)
  Услуга: Рабочая станция (КЦ)
  Вид запроса: Запрос на обслуживание
  Приоритет: (4) Низкий
  Просрочена: не просрочен
  Описание: На рабочей станции не включается. Требуется помощь....

6. СОХРАНЕНИЕ РЕЗУЛЬТАТОВ:
   ✓ Основной датасет сохранен: support_tickets_final_anonymized.csv

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [28]:
# --- 5.6 Сохранение результатов ---
print("\n6. СОХРАНЕНИЕ РЕЗУЛЬТАТОВ:")

# Явно указываем нужные колонки
columns_to_save = [
    'Дата/время регистрации',
    'Крайний срок обработки', 
    'Фактическое время выполнения',
    'Плановое время выполнения',
    'Приоритет',
    'Просрочен',
    'Результат работ',
    'Получатель услуг',
    'Инициатор',
    'Кем решен (сотрудник)',
    'Расположение',
    'Описание',
    'Услуга',
    'Вид запроса'
]

# Проверяем, что все колонки существуют
existing_columns = [col for col in columns_to_save if col in applications_anon.columns]
missing_columns = [col for col in columns_to_save if col not in applications_anon.columns]

if missing_columns:
    print(f"   ⚠️ Внимание: не найдены колонки: {missing_columns}")

print(f"   Сохраняем колонок: {len(existing_columns)}")

# Сохраняем датасет
output_file = 'support_tickets_final_anonymized.csv'
applications_anon[existing_columns].to_csv(output_file, index=False, encoding='utf-8-sig')
print(f"   ✓ Основной датасет сохранен: {output_file}")

# Показываем список сохраненных колонок
print(f"\n   📋 Сохраненные колонки:")
for i, col in enumerate(existing_columns, 1):
    print(f"      {i}. {col}")

6. СОХРАНЕНИЕ РЕЗУЛЬТАТОВ:
   Сохраняем колонок: 14
   ✓ Основной датасет сохранен: support_tickets_final_anonymized.csv

   📋 Сохраненные колонки:
      1. Дата/время регистрации
      2. Крайний срок обработки
      3. Фактическое время выполнения
      4. Плановое время выполнения
      5. Приоритет
      6. Просрочен
      7. Результат работ
      8. Получатель услуг
      9. Инициатор
      10. Кем решен (сотрудник)
      11. Расположение
      12. Описание
      13. Услуга
      14. Вид запроса