Глобально, ваша задача на итоговый проект - написать скрипт, в котором:

- Будет происходить обращение к нашему API для получения данных
- Данные будут обрабатываться и готовиться к загрузке в базу данных
- Обработанные данные будут загружаться в локальную базу PostgreSQL, которую вы развернули на своем компьютере или в облаке

- Во время обработки будет сохраняться лог работы скрипта с отлавливанием всех ошибок и выводом промежуточных стадий (например, скачивание началось / скачивание завершилось / заполнение базы началось и т.д., с трекингом времени). Лог нужно сохранять в текстовый файл. Файл нужно именовать в соответствии с текущей датой. Если в папке с логами уже есть другие логи - их необходимо удалять, оставляем только логи за последние 3 дня.

In [17]:
#postgressupabase

import requests
import pandas as pd
import ast

api_url = "https://b2b.itresume.ru/api/statistics"

params = {
    'client': 'Skillfactory'
    , 'client_key': 'M2MGWS'
    , 'start': '2023-04-01 12:46:47.860798'
    , 'end': '2023-04-01 13:46:47.860798'
}
response = requests.get(api_url, params=params)

data = response.json()
df = pd.DataFrame(data)

In [18]:
df.head(10)

                        lti_user_id  ...                  created_at
0  7f979222ff28d787603cddef8947d58c  ...  2023-04-01 12:46:50.820389
1  7e286e46c64e96477e776bea316c0c8c  ...  2023-04-01 12:46:56.065973
2  450f0b91385f24105bb412d1c9f54a47  ...  2023-04-01 12:47:09.392442
3  450f0b91385f24105bb412d1c9f54a47  ...  2023-04-01 12:47:29.698353
4  46199393d6a5b414d1ced9ca5e816c62  ...  2023-04-01 12:47:46.993542
5  450f0b91385f24105bb412d1c9f54a47  ...  2023-04-01 12:47:56.640567
6  944854991f18bf5a0273793b050ac57c  ...  2023-04-01 12:48:15.004771
7  2dce6103c7f308c31c16fcd2324d733d  ...  2023-04-01 12:48:23.773469
8  450f0b91385f24105bb412d1c9f54a47  ...  2023-04-01 12:48:31.686840
9  2dce6103c7f308c31c16fcd2324d733d  ...  2023-04-01 12:48:32.863045

[10 rows x 5 columns]

Адекватный вид

Поскольку все эти данные мы с вами должны сохранить в локальную базу - определим её структуру.


* user_id - строковый айди пользователя

* oauth_consumer_key - уникальный токен клиента

* lis_result_sourcedid - ссылка на блок, в котором находится задача в ЛМС

* lis_outcome_service_url - URL адрес в ЛМС, куда мы шлем оценку

* is_correct - была ли попытка верной (null, если это run)

* attempt_type - ран или сабмит

* created_at - дата и время попытки

In [21]:
# преобразуем строку в словарь
df['passback_dict'] = df['passback_params'].apply(ast.literal_eval)

In [22]:
# уникальный токен клиента
df['oauth_consumer_key'] = df['passback_dict'].apply(lambda x: x.get('oauth_consumer_key', ''))

In [23]:
# ссылка на блок, в котором находится задача в ЛМС
df['lis_result_sourcedid'] = df['passback_dict'].apply(lambda x: x.get('lis_result_sourcedid', ''))

In [24]:
# URL адрес в ЛМС, куда мы шлем оценку
df['lis_outcome_service_url'] = df['passback_dict'].apply(lambda x: x.get('lis_outcome_service_url', ''))

In [27]:
df_selected = df.loc[:, ['lti_user_id', 'oauth_consumer_key', 'lis_result_sourcedid', 'lis_outcome_service_url', 'is_correct', 'attempt_type', 'created_at']]

In [28]:
df_selected.head(5)

                        lti_user_id  ...                  created_at
0  7f979222ff28d787603cddef8947d58c  ...  2023-04-01 12:46:50.820389
1  7e286e46c64e96477e776bea316c0c8c  ...  2023-04-01 12:46:56.065973
2  450f0b91385f24105bb412d1c9f54a47  ...  2023-04-01 12:47:09.392442
3  450f0b91385f24105bb412d1c9f54a47  ...  2023-04-01 12:47:29.698353
4  46199393d6a5b414d1ced9ca5e816c62  ...  2023-04-01 12:47:46.993542

[5 rows x 7 columns]

In [35]:
import psycopg2

# Вставьте ваш реальный пароль вместо [YOUR-PASSWORD]
DATABASE_URL = "postgresql://postgres:postgressupabase@db.pzgkvytimcgvjxdidcoj.supabase.co:5432/postgres"
try:
    conn = psycopg2.connect(DATABASE_URL)
    print("✅ Подключение успешно!")
    
    # Проверка
    cur = conn.cursor()
    cur.execute("SELECT version();")
    print(f"Версия PostgreSQL: {cur.fetchone()[0]}")
    
    cur.close()
    conn.close()
    
except Exception as e:
    print(f"❌ Ошибка: {e}")

❌ Ошибка: could not translate host name "db.pzgkvytimcgvjxdidcoj.supabase.co" to address: nodename nor servname provided, or not known