In [1]:
import pandas as pd
import numpy as np

# загружаем входящую ВЫГРУЗКУ из СБИС

In [2]:
inbox_1 = pd.read_csv(r'C:\Users\Incognitus\Documents\git_hub\Simulate\practical_case_pandas\Входящие\Входящие 01.csv', sep=';', encoding='cp1251')

In [3]:
inbox_2 = pd.read_csv(r'C:\Users\Incognitus\Documents\git_hub\Simulate\practical_case_pandas\Входящие\Входящие 02.csv', sep=';', encoding='cp1251')

In [4]:
inbox_3 = pd.read_csv(r'C:\Users\Incognitus\Documents\git_hub\Simulate\practical_case_pandas\Входящие\Входящие 03.csv', sep=';', encoding='cp1251')

In [5]:
inbox_1.head(1)

,Дата,Номер,Сумма,Статус,Примечание,Комментарий,Контрагент,ИНН/КПП,Организация,ИНН/КПП.1,...,Время,Тип пакета,Идентификатор пакета,Запущено в обработку,Получено контрагентом,Завершено,Увеличение суммы,НДС,Уменьшение суммы,НДС.1
0,30.09.21,БРН00709545,"4 056,46",Выполнение завершено успешно,NaN,"БРН00709545 на сумму 4 056,46р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,...,23:40:56,ДокОтгрВх,76210df0-7c48-4e6d-ad2b-6cbe2f3b7722,30.09.21 23:40,01.10.21 08:39,01.10.21 14:59,"0,00","0,00","0,00","0,00"

In [6]:
inbox_2.head(1)

,Дата,Номер,Сумма,Статус,Примечание,Комментарий,Контрагент,ИНН/КПП,Организация,ИНН/КПП.1,...,Время,Тип пакета,Идентификатор пакета,Запущено в обработку,Получено контрагентом,Завершено,Увеличение суммы,НДС,Уменьшение суммы,НДС.1
0,09.12.20,10324858-30,"417,34",Выполнение завершено успешно,NaN,Интернет заказ: MA-18962181; Интернет заказ: M...,"Филиал АО НПК ""Катрен"" в г. Химки",5408130693 / 504743001,ООО Рога и Копыта,4025419873 / 402501001,...,11:05:06,ДокОтгрВх,90e7b521-7842-42a7-a55f-876cf0aec0e1,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"

In [7]:
inbox_3.head(1)

,Дата,Номер,Сумма,Статус,Примечание,Комментарий,Контрагент,ИНН/КПП,Организация,ИНН/КПП.1,...,Время,Тип пакета,Идентификатор пакета,Запущено в обработку,Получено контрагентом,Завершено,Увеличение суммы,НДС,Уменьшение суммы,НДС.1
0,13.12.19,8059548-30,"0,00",Выполнение завершено успешно,NaN,Интернет заказ: A-41612340; Интернет заказ: A-...,"Филиал АО НПК ""Катрен"" в г. Химки",5408130693 / 504743001,ООО Рога и Копыта,4025419873 / 402501001,...,18:06:10,ДокОтгрВх,287f2f6d-cef7-418a-b4a4-282de14a5141,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"

In [8]:
# проверим на совпадение имен в столбцах.
print(all(inbox_1.columns == inbox_2.columns) and all(inbox_2.columns == inbox_3.columns))

True

In [9]:
new_rename_columns = [
    "Дата",
    "Номер",
    "Сумма",
    "Статус",
    "Примечание",
    "Комментарий",
    "Контрагент",
    "ИНН/КПП",
    "Организация",
    "ИНН/КПП",
    "Тип_документа",
    "Имя_файла",
    "Дата",
    "Номер_1",
    "Сумма_1",
    "Сумма_НДС",
    "Ответственный",
    "Подразделение",
    "Код",
    "Дата",
    "Время",
    "Тип_пакета",
    "Идентификатор_пакета",
    "Запущено_в_обработку",
    "Получено_контрагентом",
    "Завершено",
    "Увеличение_суммы",
    "НДC",
    "Уменьшение_суммы",
    "НДС"
                 ]

In [10]:
# проверим длину всех входящих боксов
print(len(inbox_1))
print(len(inbox_2))
print(len(inbox_3))

100000
100000
95737

In [11]:
# объеденим все боксы
df_total_inbox = pd.concat([inbox_1, inbox_2, inbox_3], ignore_index=True)

In [12]:
# проверим длину общего массива данных.
print(len(df_total_inbox))

295737

In [13]:
df_total_inbox.columns = new_rename_columns

In [14]:
df_total_inbox.head(2)

,Дата,Номер,Сумма,Статус,Примечание,Комментарий,Контрагент,ИНН/КПП,Организация,ИНН/КПП,...,Время,Тип_пакета,Идентификатор_пакета,Запущено_в_обработку,Получено_контрагентом,Завершено,Увеличение_суммы,НДC,Уменьшение_суммы,НДС
0,30.09.21,БРН00709545,"4 056,46",Выполнение завершено успешно,NaN,"БРН00709545 на сумму 4 056,46р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,...,23:40:56,ДокОтгрВх,76210df0-7c48-4e6d-ad2b-6cbe2f3b7722,30.09.21 23:40,01.10.21 08:39,01.10.21 14:59,"0,00","0,00","0,00","0,00"
1,30.09.21,БРН00709545,"4 056,46",Выполнение завершено успешно,NaN,"БРН00709545 на сумму 4 056,46р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,...,23:40:56,ДокОтгрВх,76210df0-7c48-4e6d-ad2b-6cbe2f3b7722,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"

# загружаем Аптеки

In [15]:
pharmacy_366 = pd.read_csv(r'C:\Users\Incognitus\Documents\git_hub\Simulate\practical_case_pandas\Аптеки\csv\correct\366.csv', sep=';', encoding='cp1251')

In [16]:
pharmacy_A123 = pd.read_csv(r'C:\Users\Incognitus\Documents\git_hub\Simulate\practical_case_pandas\Аптеки\csv\correct\А123.csv', sep=';', encoding='cp1251')

In [17]:
pharmacy_366.head(2)

,№ п/п,Штрих-код партии,Наименование товара,Поставщик,Дата приходного документа,Номер приходного документа,Дата накладной,Номер накладной,Кол-во,Сумма в закупочных ценах без НДС,Ставка НДС поставщика,Сумма НДС,Сумма в закупочных ценах с НДС
0,1,200200060311,СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. Р.S №100 (50П...,Катрен г.Химки,26.05.2021,2002088.0,25.05.2021,4665120-30,0.04,33.65,10%,3.37,37.02
1,2,200801594420,КОСМОПОР ПОВЯЗКА 10СМХ6СМ №25 П/ОПЕР. САМОКЛ. ...,Здравсервис,25.03.2020,9000479.8,25.03.2020,E7914339/27806739,0.04,27.58,10%,2.76,30.34

In [18]:
pharmacy_366.columns

Index(['№ п/п', 'Штрих-код партии', 'Наименование товара', 'Поставщик',
       'Дата приходного документа', 'Номер приходного документа',
       'Дата накладной', 'Номер накладной', 'Кол-во',
       'Сумма в закупочных ценах без НДС', 'Ставка НДС поставщика',
       'Сумма НДС', 'Сумма в закупочных ценах с НДС'],
      dtype='object')

In [19]:
pharmacy_A123.head(2)

,№ п/п,Штрих-код партии,Наименование товара,Поставщик,Дата приходного документа,Номер приходного документа,Дата накладной,Номер накладной,Кол-во,Сумма в закупочных ценах без НДС,Ставка НДС поставщика,Сумма НДС,Сумма в закупочных ценах с НДС
0,1,201300039533,СФМ ПЕРЧАТКИ СМОТР. ГОЛУБЫЕ Н/СТЕР. НИТРИЛ Р.L...,Катрен г.Химки,19.04.2021,13001265.0,18.04.2021,3541290-30,0.02,36.48,10%,3.65,40.13
1,2,201300052321,ХАРТМАНН КОСМОПОР Е ПОВЯЗКА 15СМХ8СМ №25 П/ОПЕ...,Фармкомплект ООО,17.08.2021,13002787.0,16.08.2021,ФК003216604,0.04,18.43,10%,1.84,20.28

In [20]:
pharmacy_A123.columns

Index(['№ п/п', 'Штрих-код партии', 'Наименование товара', 'Поставщик',
       'Дата приходного документа', 'Номер приходного документа',
       'Дата накладной', 'Номер накладной', 'Кол-во',
       'Сумма в закупочных ценах без НДС', 'Ставка НДС поставщика',
       'Сумма НДС', 'Сумма в закупочных ценах с НДС'],
      dtype='object')

In [21]:
pharmacy_366.columns == pharmacy_A123.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [22]:
# объеденим все боксы
df_total_pharmacy = pd.concat([pharmacy_366, pharmacy_A123], ignore_index=True)

In [23]:
df_total_pharmacy.head(3)

,№ п/п,Штрих-код партии,Наименование товара,Поставщик,Дата приходного документа,Номер приходного документа,Дата накладной,Номер накладной,Кол-во,Сумма в закупочных ценах без НДС,Ставка НДС поставщика,Сумма НДС,Сумма в закупочных ценах с НДС
0,1,200200060311,СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. Р.S №100 (50П...,Катрен г.Химки,26.05.2021,2002088.0,25.05.2021,4665120-30,0.040000,33.65,10%,3.37,37.02
1,2,200801594420,КОСМОПОР ПОВЯЗКА 10СМХ6СМ №25 П/ОПЕР. САМОКЛ. ...,Здравсервис,25.03.2020,9000479.8,25.03.2020,E7914339/27806739,0.040000,27.58,10%,2.76,30.34
2,3,200200075091,ХАРТМАНН БРАНОЛИНД H ПОВЯЗКА СТЕР. 10Х20СМ. №3...,Протек,01.09.2021,2003451.0,01.09.2021,164621235-001,0.066667,145.28,10%,14.53,159.81

In [24]:
df_total_pharmacy["Номер счет-фактуры"] = None
df_total_pharmacy["Сумма счет-фактуры"] = None
df_total_pharmacy["Дата счет-фактуры"] = None
df_total_pharmacy["Сравнение дат"] = None

In [25]:
target = 'ЕАПТЕКА'

mask = df_total_pharmacy['Поставщик'].str.contains(target, case=False, na=False)

df_total_pharmacy['Номер накладной'] = np.where(mask, 
                                                 df_total_pharmacy['Номер накладной'] + '/15', 
                                                 df_total_pharmacy['Номер накладной'])

In [26]:
# target = 'ЕАПТЕКА'
# df_total_pharmacy.query('Поставщик.str.contains(@target, case=False, na=False)').head(2)

In [27]:
df_total_pharmacy.head(2)

,№ п/п,Штрих-код партии,Наименование товара,Поставщик,Дата приходного документа,Номер приходного документа,Дата накладной,Номер накладной,Кол-во,Сумма в закупочных ценах без НДС,Ставка НДС поставщика,Сумма НДС,Сумма в закупочных ценах с НДС,Номер счет-фактуры,Сумма счет-фактуры,Дата счет-фактуры,Сравнение дат
0,1,200200060311,СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. Р.S №100 (50П...,Катрен г.Химки,26.05.2021,2002088.0,25.05.2021,4665120-30,0.04,33.65,10%,3.37,37.02,None,None,None,None
1,2,200801594420,КОСМОПОР ПОВЯЗКА 10СМХ6СМ №25 П/ОПЕР. САМОКЛ. ...,Здравсервис,25.03.2020,9000479.8,25.03.2020,E7914339/27806739,0.04,27.58,10%,2.76,30.34,None,None,None,None

In [28]:
df_total_inbox = df_total_inbox.loc[:, ~df_total_inbox.columns.duplicated()]
df_total_inbox.head(2)

,Дата,Номер,Сумма,Статус,Примечание,Комментарий,Контрагент,ИНН/КПП,Организация,Тип_документа,...,Время,Тип_пакета,Идентификатор_пакета,Запущено_в_обработку,Получено_контрагентом,Завершено,Увеличение_суммы,НДC,Уменьшение_суммы,НДС
0,30.09.21,БРН00709545,"4 056,46",Выполнение завершено успешно,NaN,"БРН00709545 на сумму 4 056,46р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,ЭДОНакл,...,23:40:56,ДокОтгрВх,76210df0-7c48-4e6d-ad2b-6cbe2f3b7722,30.09.21 23:40,01.10.21 08:39,01.10.21 14:59,"0,00","0,00","0,00","0,00"
1,30.09.21,БРН00709545,"4 056,46",Выполнение завершено успешно,NaN,"БРН00709545 на сумму 4 056,46р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,СчФктр,...,23:40:56,ДокОтгрВх,76210df0-7c48-4e6d-ad2b-6cbe2f3b7722,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"

In [29]:
# Из найденных строк нужно оставить только те, которые имеют один из типов документа: ["СчФктр", "УпдДоп", "УпдСчфДоп", "ЭДОНакл"]

In [30]:
df_total_pharmacy.columns = ['№_п/п', 'Штрих-код_партии', 'Наименование_товара', 'Поставщик',
       'Дата_приходного_документа', 'Номер_приходного_документа',
       'Дата_накладной', 'Номер_накладной', 'Кол-во',
       'Сумма_в_закупочных_ценах_без_НДС', 'Ставка_НДС_поставщика',
       'Сумма_НДС', 'Сумма_в_закупочных_ценах_с_НДС', 'Номер_счет-фактуры',
       'Сумма_счет-фактуры', 'Дата_счет-фактуры', 'Сравнение_дат']

In [31]:
target_columns_type_doc = ["СчФктр", "УпдДоп", "УпдСчфДоп", "ЭДОНакл"]
df_total_inbox_filter = df_total_inbox.query('Тип_документа in @target_columns_type_doc')

target_columns_no = df_total_inbox_filter['Номер'].to_list()
df_total_pharmacy_filter = df_total_pharmacy.query('Номер_накладной in @target_columns_no')

In [36]:
df_total_pharmacy_filter.head(2)

,№_п/п,Штрих-код_партии,Наименование_товара,Поставщик,Дата_приходного_документа,Номер_приходного_документа,Дата_накладной,Номер_накладной,Кол-во,Сумма_в_закупочных_ценах_без_НДС,Ставка_НДС_поставщика,Сумма_НДС,Сумма_в_закупочных_ценах_с_НДС,Номер_счет-фактуры,Сумма_счет-фактуры,Дата_счет-фактуры,Сравнение_дат
0,1,200200060311,СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. Р.S №100 (50П...,Катрен г.Химки,26.05.2021,2002088.0,25.05.2021,4665120-30,0.04,33.65,10%,3.37,37.02,4665120-30,4665120-30,None,None
1,2,200801594420,КОСМОПОР ПОВЯЗКА 10СМХ6СМ №25 П/ОПЕР. САМОКЛ. ...,Здравсервис,25.03.2020,9000479.8,25.03.2020,E7914339/27806739,0.04,27.58,10%,2.76,30.34,E7914339/27806739,E7914339/27806739,None,None

In [33]:
#OK Если "Поставщик" - ЕАПТЕКА, то к "Номер накладной" нужно добавить /15.
#OK Нужно найти все записи в выгрузке из СБИСа по данному номеру накладной
#OK Из найденных строк нужно оставить только те, которые имеют один из типов документа: ["СчФктр", "УпдДоп", "УпдСчфДоп", "ЭДОНакл"]
#OK Если ничего не найдено - просто переходим к следующей строке
#? Если найдено - нужно сохранить значения Номер, Сумма и Дата
#? Дату нужно представить в формате 25.05.2021
# В столбцы из пункта 5 нужно записать найденные для данной строки значения
# В столбец Сравнение дат помещаем "Не совпадает!", если найденная дата и дата накладной отличаются. Иначе - пустая строка.
# Обратите внимание: если по заданным условиям находится несколько подходящих документов - выбираем значения из первого найденного. Это означает, что если у документов разные суммы, берется та, что стоит первой в выгрузке из СБИС.

# Если дата счет фактуры отсутствует или пуста, а дата накладной заполнена, такая ситуация считается расхождением.

In [34]:
df_total_pharmacy_filter.columns

Index(['№_п/п', 'Штрих-код_партии', 'Наименование_товара', 'Поставщик',
       'Дата_приходного_документа', 'Номер_приходного_документа',
       'Дата_накладной', 'Номер_накладной', 'Кол-во',
       'Сумма_в_закупочных_ценах_без_НДС', 'Ставка_НДС_поставщика',
       'Сумма_НДС', 'Сумма_в_закупочных_ценах_с_НДС', 'Номер_счет-фактуры',
       'Сумма_счет-фактуры', 'Дата_счет-фактуры', 'Сравнение_дат'],
      dtype='object')

In [37]:
df_total_pharmacy_filter['Номер_счет-фактуры'] = df_total_pharmacy_filter['Номер_накладной']
df_total_pharmacy_filter['Сумма_счет-фактуры'] = df_total_pharmacy_filter['Сумма_НДС']
df_total_pharmacy_filter['Дата_счет-фактуры'] = df_total_pharmacy_filter['Дата_накладной']

C:\Users\Incognitus\AppData\Local\Temp\ipykernel_2652\665107074.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_total_pharmacy_filter['Номер_счет-фактуры'] = df_total_pharmacy_filter['Номер_накладной']
C:\Users\Incognitus\AppData\Local\Temp\ipykernel_2652\665107074.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_total_pharmacy_filter['Сумма_счет-фактуры'] = df_total_pharmacy_filter['Сумма_НДС']
C:\Users\Incognitus\AppData\Local\Temp\ipykernel_2652\665107074.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_total_pharmacy_filter['Дата_счет-фактуры'] = df_total_pharmacy_filter['Дата_накладной']

In [39]:
df_total_pharmacy_filter['Дата_счет-фактуры'] = pd.to_datetime(df_total_pharmacy_filter['Дата_счет-фактуры'], format="%d.%m.%Y")

C:\Users\Incognitus\AppData\Local\Temp\ipykernel_2652\3868325390.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_total_pharmacy_filter['Дата_счет-фактуры'] = pd.to_datetime(df_total_pharmacy_filter['Дата_счет-фактуры'], format="%d.%m.%Y")

In [40]:
df_total_pharmacy_filter.head(3)

,№_п/п,Штрих-код_партии,Наименование_товара,Поставщик,Дата_приходного_документа,Номер_приходного_документа,Дата_накладной,Номер_накладной,Кол-во,Сумма_в_закупочных_ценах_без_НДС,Ставка_НДС_поставщика,Сумма_НДС,Сумма_в_закупочных_ценах_с_НДС,Номер_счет-фактуры,Сумма_счет-фактуры,Дата_счет-фактуры,Сравнение_дат
0,1,200200060311,СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. Р.S №100 (50П...,Катрен г.Химки,26.05.2021,2002088.0,25.05.2021,4665120-30,0.040000,33.65,10%,3.37,37.02,4665120-30,3.37,2021-05-25,None
1,2,200801594420,КОСМОПОР ПОВЯЗКА 10СМХ6СМ №25 П/ОПЕР. САМОКЛ. ...,Здравсервис,25.03.2020,9000479.8,25.03.2020,E7914339/27806739,0.040000,27.58,10%,2.76,30.34,E7914339/27806739,2.76,2020-03-25,None
2,3,200200075091,ХАРТМАНН БРАНОЛИНД H ПОВЯЗКА СТЕР. 10Х20СМ. №3...,Протек,01.09.2021,2003451.0,01.09.2021,164621235-001,0.066667,145.28,10%,14.53,159.81,164621235-001,14.53,2021-09-01,None

In [38]:
pd.to_datetime?

Signature:
pd.to_datetime(
    arg: 'DatetimeScalarOrArrayConvertible | DictConvertible',
    errors: 'DateTimeErrorChoices' = 'raise',
    dayfirst: 'bool' = False,
    yearfirst: 'bool' = False,
    utc: 'bool' = False,
    format: 'str | None' = None,
    exact: 'bool | lib.NoDefault' = <no_default>,
    unit: 'str | None' = None,
    infer_datetime_format: 'lib.NoDefault | bool' = <no_default>,
    origin: 'str' = 'unix',
    cache: 'bool' = True,
) -> 'DatetimeIndex | Series | DatetimeScalar | NaTType | None'
Docstring:
Convert argument to datetime.

This function converts a scalar, array-like, :class:`Series` or
:class:`DataFrame`/dict-like to a pandas datetime object.

Parameters
----------
arg : int, float, str, datetime, list, tuple, 1-d array, Series, DataFrame/dict-like
    The object to convert to a datetime. If a :class:`DataFrame` is provided, the
    method expects minimally the following columns: :const:`"year"`,
    :const:`"month"`, :const:`"day"`. The column "year"
    must be specified in 4-digit format.
errors : {'ignore', 'raise', 'coerce'}, default 'raise'
    - If :const:`'raise'`, then invalid parsing will raise an exception.
    - If :const:`'coerce'`, then invalid parsing will be set as :const:`NaT`.
    - If :const:`'ignore'`, then invalid parsing will return the input.
dayfirst : bool, default False
    Specify a date parse order if `arg` is str or is list-like.
    If :const:`True`, parses dates with the day first, e.g. :const:`"10/11/12"`
    is parsed as :const:`2012-11-10`.

    .. warning::

        ``dayfirst=True`` is not strict, but will prefer to parse
        with day first.

yearfirst : bool, default False
    Specify a date parse order if `arg` is str or is list-like.

    - If :const:`True` parses dates with the year first, e.g.
      :const:`"10/11/12"` is parsed as :const:`2010-11-12`.
    - If both `dayfirst` and `yearfirst` are :const:`True`, `yearfirst` is
      preceded (same as :mod:`dateutil`).

    .. warning::

        ``yearfirst=True`` is not strict, but will prefer to parse
        with year first.

utc : bool, default False
    Control timezone-related parsing, localization and conversion.

    - If :const:`True`, the function *always* returns a timezone-aware
      UTC-localized :class:`Timestamp`, :class:`Series` or
      :class:`DatetimeIndex`. To do this, timezone-naive inputs are
      *localized* as UTC, while timezone-aware inputs are *converted* to UTC.

    - If :const:`False` (default), inputs will not be coerced to UTC.
      Timezone-naive inputs will remain naive, while timezone-aware ones
      will keep their time offsets. Limitations exist for mixed
      offsets (typically, daylight savings), see :ref:`Examples
      <to_datetime_tz_examples>` section for details.

    .. warning::

        In a future version of pandas, parsing datetimes with mixed time
        zones will raise an error unless `utc=True`.
        Please specify `utc=True` to opt in to the new behaviour
        and silence this warning. To create a `Series` with mixed offsets and
        `object` dtype, please use `apply` and `datetime.datetime.strptime`.

    See also: pandas general documentation about `timezone conversion and
    localization
    <https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html
    #time-zone-handling>`_.

format : str, default None
    The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
    `strftime documentation
    <https://docs.python.org/3/library/datetime.html
    #strftime-and-strptime-behavior>`_ for more information on choices, though
    note that :const:`"%f"` will parse all the way up to nanoseconds.
    You can also pass:

    - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
      time string (not necessarily in exactly the same format);
    - "mixed", to infer the format for each element individually. This is risky,
      and you should probably use it along with `dayfirst`.

    .. note::

        If a :class:`DataFrame` is passed, then `format` has no effect.

exact : bool, default True
    Control how `format` is used:

    - If :const:`True`, require an exact `format` match.
    - If :const:`False`, allow the `format` to match anywhere in the target
      string.

    Cannot be used alongside ``format='ISO8601'`` or ``format='mixed'``.
unit : str, default 'ns'
    The unit of the arg (D,s,ms,us,ns) denote the unit, which is an
    integer or float number. This will be based off the origin.
    Example, with ``unit='ms'`` and ``origin='unix'``, this would calculate
    the number of milliseconds to the unix epoch start.
infer_datetime_format : bool, default False
    If :const:`True` and no `format` is given, attempt to infer the format
    of the datetime strings based on the first non-NaN element,
    and if it can be inferred, switch to a faster method of parsing them.
    In some cases this can increase the parsing speed by ~5-10x.

    .. deprecated:: 2.0.0
        A strict version of this argument is now the default, passing it has
        no effect.

origin : scalar, default 'unix'
    Define the reference date. The numeric values would be parsed as number
    of units (defined by `unit`) since this reference date.

    - If :const:`'unix'` (or POSIX) time; origin is set to 1970-01-01.
    - If :const:`'julian'`, unit must be :const:`'D'`, and origin is set to
      beginning of Julian Calendar. Julian day number :const:`0` is assigned
      to the day starting at noon on January 1, 4713 BC.
    - If Timestamp convertible (Timestamp, dt.datetime, np.datetimt64 or date
      string), origin is set to Timestamp identified by origin.
    - If a float or integer, origin is the difference
      (in units determined by the ``unit`` argument) relative to 1970-01-01.
cache : bool, default True
    If :const:`True`, use a cache of unique, converted dates to apply the
    datetime conversion. May produce significant speed-up when parsing
    duplicate date strings, especially ones with timezone offsets. The cache
    is only used when there are at least 50 values. The presence of
    out-of-bounds values will render the cache unusable and may slow down
    parsing.

Returns
-------
datetime
    If parsing succeeded.
    Return type depends on input (types in parenthesis correspond to
    fallback in case of unsuccessful timezone or out-of-range timestamp
    parsing):

    - scalar: :class:`Timestamp` (or :class:`datetime.datetime`)
    - array-like: :class:`DatetimeIndex` (or :class:`Series` with
      :class:`object` dtype containing :class:`datetime.datetime`)
    - Series: :class:`Series` of :class:`datetime64` dtype (or
      :class:`Series` of :class:`object` dtype containing
      :class:`datetime.datetime`)
    - DataFrame: :class:`Series` of :class:`datetime64` dtype (or
      :class:`Series` of :class:`object` dtype containing
      :class:`datetime.datetime`)

Raises
------
ParserError
    When parsing a date from string fails.
ValueError
    When another datetime conversion error happens. For example when one
    of 'year', 'month', day' columns is missing in a :class:`DataFrame`, or
    when a Timezone-aware :class:`datetime.datetime` is found in an array-like
    of mixed time offsets, and ``utc=False``.

See Also
--------
DataFrame.astype : Cast argument to a specified dtype.
to_timedelta : Convert argument to timedelta.
convert_dtypes : Convert dtypes.

Notes
-----

Many input types are supported, and lead to different output types:

- **scalars** can be int, float, str, datetime object (from stdlib :mod:`datetime`
  module or :mod:`numpy`). They are converted to :class:`Timestamp` when
  possible, otherwise they are converted to :class:`datetime.datetime`.
  None/NaN/null scalars are converted to :const:`NaT`.

- **array-like** can contain int, float, str, datetime objects. They are
  converted to :class:`DatetimeIndex` when possible, otherwise they are
  converted to :class:`Index` with :class:`object` dtype, containing
  :class:`datetime.datetime`. None/NaN/null entries are converted to
  :const:`NaT` in both cases.

- **Series** are converted to :class:`Series` with :class:`datetime64`
  dtype when possible, otherwise they are converted to :class:`Series` with
  :class:`object` dtype, containing :class:`datetime.datetime`. None/NaN/null
  entries are converted to :const:`NaT` in both cases.

- **DataFrame/dict-like** are converted to :class:`Series` with
  :class:`datetime64` dtype. For each row a datetime is created from assembling
  the various dataframe columns. Column keys can be common abbreviations
  like ['year', 'month', 'day', 'minute', 'second', 'ms', 'us', 'ns']) or
  plurals of the same.

The following causes are responsible for :class:`datetime.datetime` objects
being returned (possibly inside an :class:`Index` or a :class:`Series` with
:class:`object` dtype) instead of a proper pandas designated type
(:class:`Timestamp`, :class:`DatetimeIndex` or :class:`Series`
with :class:`datetime64` dtype):

- when any input element is before :const:`Timestamp.min` or after
  :const:`Timestamp.max`, see `timestamp limitations
  <https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html
  #timeseries-timestamp-limits>`_.

- when ``utc=False`` (default) and the input is an array-like or
  :class:`Series` containing mixed naive/aware datetime, or aware with mixed
  time offsets. Note that this happens in the (quite frequent) situation when
  the timezone has a daylight savings policy. In that case you may wish to
  use ``utc=True``.

Examples
--------

**Handling various input formats**

Assembling a datetime from multiple columns of a :class:`DataFrame`. The keys
can be common abbreviations like ['year', 'month', 'day', 'minute', 'second',
'ms', 'us', 'ns']) or plurals of the same

>>> df = pd.DataFrame({'year': [2015, 2016],
...                    'month': [2, 3],
...                    'day': [4, 5]})
>>> pd.to_datetime(df)
0   2015-02-04
1   2016-03-05
dtype: datetime64[ns]

Using a unix epoch time

>>> pd.to_datetime(1490195805, unit='s')
Timestamp('2017-03-22 15:16:45')
>>> pd.to_datetime(1490195805433502912, unit='ns')
Timestamp('2017-03-22 15:16:45.433502912')

.. warning:: For float arg, precision rounding might happen. To prevent
    unexpected behavior use a fixed-width exact type.

Using a non-unix epoch origin

>>> pd.to_datetime([1, 2, 3], unit='D',
...                origin=pd.Timestamp('1960-01-01'))
DatetimeIndex(['1960-01-02', '1960-01-03', '1960-01-04'],
              dtype='datetime64[ns]', freq=None)

**Differences with strptime behavior**

:const:`"%f"` will parse all the way up to nanoseconds.

>>> pd.to_datetime('2018-10-26 12:00:00.0000000011',
...                format='%Y-%m-%d %H:%M:%S.%f')
Timestamp('2018-10-26 12:00:00.000000001')

**Non-convertible date/times**

Passing ``errors='coerce'`` will force an out-of-bounds date to :const:`NaT`,
in addition to forcing non-dates (or non-parseable dates) to :const:`NaT`.

>>> pd.to_datetime('13000101', format='%Y%m%d', errors='coerce')
NaT

.. _to_datetime_tz_examples:

**Timezones and time offsets**

The default behaviour (``utc=False``) is as follows:

- Timezone-naive inputs are converted to timezone-naive :class:`DatetimeIndex`:

>>> pd.to_datetime(['2018-10-26 12:00:00', '2018-10-26 13:00:15'])
DatetimeIndex(['2018-10-26 12:00:00', '2018-10-26 13:00:15'],
              dtype='datetime64[ns]', freq=None)

- Timezone-aware inputs *with constant time offset* are converted to
  timezone-aware :class:`DatetimeIndex`:

>>> pd.to_datetime(['2018-10-26 12:00 -0500', '2018-10-26 13:00 -0500'])
DatetimeIndex(['2018-10-26 12:00:00-05:00', '2018-10-26 13:00:00-05:00'],
              dtype='datetime64[ns, UTC-05:00]', freq=None)

- However, timezone-aware inputs *with mixed time offsets* (for example
  issued from a timezone with daylight savings, such as Europe/Paris)
  are **not successfully converted** to a :class:`DatetimeIndex`.
  Parsing datetimes with mixed time zones will show a warning unless
  `utc=True`. If you specify `utc=False` the warning below will be shown
  and a simple :class:`Index` containing :class:`datetime.datetime`
  objects will be returned:

>>> pd.to_datetime(['2020-10-25 02:00 +0200',
...                 '2020-10-25 04:00 +0100'])  # doctest: +SKIP
FutureWarning: In a future version of pandas, parsing datetimes with mixed
time zones will raise an error unless `utc=True`. Please specify `utc=True`
to opt in to the new behaviour and silence this warning. To create a `Series`
with mixed offsets and `object` dtype, please use `apply` and
`datetime.datetime.strptime`.
Index([2020-10-25 02:00:00+02:00, 2020-10-25 04:00:00+01:00],
      dtype='object')

- A mix of timezone-aware and timezone-naive inputs is also converted to
  a simple :class:`Index` containing :class:`datetime.datetime` objects:

>>> from datetime import datetime
>>> pd.to_datetime(["2020-01-01 01:00:00-01:00",
...                 datetime(2020, 1, 1, 3, 0)])  # doctest: +SKIP
FutureWarning: In a future version of pandas, parsing datetimes with mixed
time zones will raise an error unless `utc=True`. Please specify `utc=True`
to opt in to the new behaviour and silence this warning. To create a `Series`
with mixed offsets and `object` dtype, please use `apply` and
`datetime.datetime.strptime`.
Index([2020-01-01 01:00:00-01:00, 2020-01-01 03:00:00], dtype='object')

|

Setting ``utc=True`` solves most of the above issues:

- Timezone-naive inputs are *localized* as UTC

>>> pd.to_datetime(['2018-10-26 12:00', '2018-10-26 13:00'], utc=True)
DatetimeIndex(['2018-10-26 12:00:00+00:00', '2018-10-26 13:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq=None)

- Timezone-aware inputs are *converted* to UTC (the output represents the
  exact same datetime, but viewed from the UTC time offset `+00:00`).

>>> pd.to_datetime(['2018-10-26 12:00 -0530', '2018-10-26 12:00 -0500'],
...                utc=True)
DatetimeIndex(['2018-10-26 17:30:00+00:00', '2018-10-26 17:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq=None)

- Inputs can contain both string or datetime, the above
  rules still apply

>>> pd.to_datetime(['2018-10-26 12:00', datetime(2020, 1, 1, 18)], utc=True)
DatetimeIndex(['2018-10-26 12:00:00+00:00', '2020-01-01 18:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq=None)
File:      c:\users\incognitus\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py
Type:      function