In [2]:
import pandas as pd

# загружаем входящую ВЫГРУЗКУ из СБИС

In [9]:
inbox_1 = pd.read_csv(r'C:\Users\Incognitus\Documents\git_hub\Simulate\practical_case_pandas\Входящие\Входящие 01.csv', sep=';', encoding='cp1251')

In [12]:
inbox_2 = pd.read_csv(r'C:\Users\Incognitus\Documents\git_hub\Simulate\practical_case_pandas\Входящие\Входящие 02.csv', sep=';', encoding='cp1251')

In [13]:
inbox_3 = pd.read_csv(r'C:\Users\Incognitus\Documents\git_hub\Simulate\practical_case_pandas\Входящие\Входящие 03.csv', sep=';', encoding='cp1251')

In [17]:
inbox_1.head(1)

,Дата,Номер,Сумма,Статус,Примечание,Комментарий,Контрагент,ИНН/КПП,Организация,ИНН/КПП.1,...,Время,Тип пакета,Идентификатор пакета,Запущено в обработку,Получено контрагентом,Завершено,Увеличение суммы,НДС,Уменьшение суммы,НДС.1
0,30.09.21,БРН00709545,"4 056,46",Выполнение завершено успешно,NaN,"БРН00709545 на сумму 4 056,46р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,...,23:40:56,ДокОтгрВх,76210df0-7c48-4e6d-ad2b-6cbe2f3b7722,30.09.21 23:40,01.10.21 08:39,01.10.21 14:59,"0,00","0,00","0,00","0,00"

In [18]:
inbox_2.head(1)

,Дата,Номер,Сумма,Статус,Примечание,Комментарий,Контрагент,ИНН/КПП,Организация,ИНН/КПП.1,...,Время,Тип пакета,Идентификатор пакета,Запущено в обработку,Получено контрагентом,Завершено,Увеличение суммы,НДС,Уменьшение суммы,НДС.1
0,09.12.20,10324858-30,"417,34",Выполнение завершено успешно,NaN,Интернет заказ: MA-18962181; Интернет заказ: M...,"Филиал АО НПК ""Катрен"" в г. Химки",5408130693 / 504743001,ООО Рога и Копыта,4025419873 / 402501001,...,11:05:06,ДокОтгрВх,90e7b521-7842-42a7-a55f-876cf0aec0e1,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"

In [19]:
inbox_3.head(1)

,Дата,Номер,Сумма,Статус,Примечание,Комментарий,Контрагент,ИНН/КПП,Организация,ИНН/КПП.1,...,Время,Тип пакета,Идентификатор пакета,Запущено в обработку,Получено контрагентом,Завершено,Увеличение суммы,НДС,Уменьшение суммы,НДС.1
0,13.12.19,8059548-30,"0,00",Выполнение завершено успешно,NaN,Интернет заказ: A-41612340; Интернет заказ: A-...,"Филиал АО НПК ""Катрен"" в г. Химки",5408130693 / 504743001,ООО Рога и Копыта,4025419873 / 402501001,...,18:06:10,ДокОтгрВх,287f2f6d-cef7-418a-b4a4-282de14a5141,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"

In [26]:
# проверим на совпадение имен в столбцах.
print(all(inbox_1.columns == inbox_2.columns) and all(inbox_2.columns == inbox_3.columns))

True

In [37]:
new_rename_columns = [
    "Дата",
    "Номер",
    "Сумма",
    "Статус",
    "Примечание",
    "Комментарий",
    "Контрагент",
    "ИНН/КПП",
    "Организация",
    "ИНН/КПП",
    "Тип_документа",
    "Имя_файла",
    "Дата",
    "Номер_1",
    "Сумма_1",
    "Сумма_НДС",
    "Ответственный",
    "Подразделение",
    "Код",
    "Дата",
    "Время",
    "Тип_пакета",
    "Идентификатор_пакета",
    "Запущено_в_обработку",
    "Получено_контрагентом",
    "Завершено",
    "Увеличение_суммы",
    "НДC",
    "Уменьшение_суммы",
    "НДС"
                 ]

In [32]:
# проверим длину всех входящих боксов
print(len(inbox_1))
print(len(inbox_2))
print(len(inbox_3))

100000
100000
95737

In [42]:
# объеденим все боксы
df_total_inbox = pd.concat([inbox_1, inbox_2, inbox_3], ignore_index=True)

In [43]:
# проверим длину общего массива данных.
print(len(df_total))

295737

In [44]:
df_total.columns = new_rename_columns

In [45]:
df_total.head(2)

,Дата,Номер,Сумма,Статус,Примечание,Комментарий,Контрагент,ИНН/КПП,Организация,ИНН/КПП,...,Время,Тип_пакета,Идентификатор_пакета,Запущено_в_обработку,Получено_контрагентом,Завершено,Увеличение_суммы,НДC,Уменьшение_суммы,НДС
0,30.09.21,БРН00709545,"4 056,46",Выполнение завершено успешно,NaN,"БРН00709545 на сумму 4 056,46р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,...,23:40:56,ДокОтгрВх,76210df0-7c48-4e6d-ad2b-6cbe2f3b7722,30.09.21 23:40,01.10.21 08:39,01.10.21 14:59,"0,00","0,00","0,00","0,00"
1,30.09.21,БРН00709545,"4 056,46",Выполнение завершено успешно,NaN,"БРН00709545 на сумму 4 056,46р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,...,23:40:56,ДокОтгрВх,76210df0-7c48-4e6d-ad2b-6cbe2f3b7722,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"

# загружаем Аптеки

In [48]:
pharmacy_366 = pd.read_csv(r'C:\Users\Incognitus\Documents\git_hub\Simulate\practical_case_pandas\Аптеки\csv\correct\366.csv', sep=';', encoding='cp1251')

In [51]:
pharmacy_A123 = pd.read_csv(r'C:\Users\Incognitus\Documents\git_hub\Simulate\practical_case_pandas\Аптеки\csv\correct\А123.csv', sep=';', encoding='cp1251')

In [52]:
pharmacy_366.head(2)

,№ п/п,Штрих-код партии,Наименование товара,Поставщик,Дата приходного документа,Номер приходного документа,Дата накладной,Номер накладной,Кол-во,Сумма в закупочных ценах без НДС,Ставка НДС поставщика,Сумма НДС,Сумма в закупочных ценах с НДС
0,1,200200060311,СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. Р.S №100 (50П...,Катрен г.Химки,26.05.2021,2002088.0,25.05.2021,4665120-30,0.04,33.65,10%,3.37,37.02
1,2,200801594420,КОСМОПОР ПОВЯЗКА 10СМХ6СМ №25 П/ОПЕР. САМОКЛ. ...,Здравсервис,25.03.2020,9000479.8,25.03.2020,E7914339/27806739,0.04,27.58,10%,2.76,30.34

In [53]:
pharmacy_A123.head(2)

,№ п/п,Штрих-код партии,Наименование товара,Поставщик,Дата приходного документа,Номер приходного документа,Дата накладной,Номер накладной,Кол-во,Сумма в закупочных ценах без НДС,Ставка НДС поставщика,Сумма НДС,Сумма в закупочных ценах с НДС
0,1,201300039533,СФМ ПЕРЧАТКИ СМОТР. ГОЛУБЫЕ Н/СТЕР. НИТРИЛ Р.L...,Катрен г.Химки,19.04.2021,13001265.0,18.04.2021,3541290-30,0.02,36.48,10%,3.65,40.13
1,2,201300052321,ХАРТМАНН КОСМОПОР Е ПОВЯЗКА 15СМХ8СМ №25 П/ОПЕ...,Фармкомплект ООО,17.08.2021,13002787.0,16.08.2021,ФК003216604,0.04,18.43,10%,1.84,20.28

In [54]:
pharmacy_366.columns == pharmacy_A123.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [55]:
# объеденим все боксы
df_total_pharmacy = pd.concat([pharmacy_366, pharmacy_A123], ignore_index=True)

In [58]:
df_total_pharmacy.head(3)

,№ п/п,Штрих-код партии,Наименование товара,Поставщик,Дата приходного документа,Номер приходного документа,Дата накладной,Номер накладной,Кол-во,Сумма в закупочных ценах без НДС,Ставка НДС поставщика,Сумма НДС,Сумма в закупочных ценах с НДС
0,1,200200060311,СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. Р.S №100 (50П...,Катрен г.Химки,26.05.2021,2002088.0,25.05.2021,4665120-30,0.040000,33.65,10%,3.37,37.02
1,2,200801594420,КОСМОПОР ПОВЯЗКА 10СМХ6СМ №25 П/ОПЕР. САМОКЛ. ...,Здравсервис,25.03.2020,9000479.8,25.03.2020,E7914339/27806739,0.040000,27.58,10%,2.76,30.34
2,3,200200075091,ХАРТМАНН БРАНОЛИНД H ПОВЯЗКА СТЕР. 10Х20СМ. №3...,Протек,01.09.2021,2003451.0,01.09.2021,164621235-001,0.066667,145.28,10%,14.53,159.81

In [60]:
df_total_pharmacy["Номер счет-фактуры"] = None
df_total_pharmacy["Сумма счет-фактуры"] = None
df_total_pharmacy["Дата счет-фактуры"] = None
df_total_pharmacy["Сравнение дат"] = None